import type { LiteraryAward } from "@/types/literary-awards";

export const LITERARY_AWARDS: LiteraryAward[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. 本屋大賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "honya-taisho",
    name: "本屋大賞",
    officialName: "本屋大賞",
    description:
      "全国の書店員が「売りたい本」を選ぶ賞。2004年創設。読者に最も愛される作品に贈られ、受賞作は必ずといっていいほどベストセラーになる。",
    icon: "📚",
    accentColor: "amber",
    startYear: 2004,
    frequency: "annual",
    announcementMonth: 4,
    prestige: "major",
    winners: [
      {
        title: "博士の愛した数式",
        author: "小川洋子",
        year: 2004,
        session: 1,
        category: "grand_prize",
        genre: "novel",
        description: "記憶が80分しか続かない元数学者と家政婦・少年の心温まる交流を描いた純愛小説。数字と人情が織り成す感動作。",
        themes: ["数学", "記憶", "純愛"],
        amazonKeyword: "博士の愛した数式 小川洋子",
      },
      {
        title: "夜のピクニック",
        author: "恩田陸",
        year: 2005,
        session: 2,
        category: "grand_prize",
        genre: "novel",
        description: "高校生たちが一夜をかけて80kmを歩く伝統行事を舞台にした青春小説。友情と淡い恋心、秘密が交差する一夜の物語。",
        themes: ["青春", "友情", "成長"],
        amazonKeyword: "夜のピクニック 恩田陸",
      },
      {
        title: "東京タワー",
        author: "リリー・フランキー",
        year: 2006,
        session: 3,
        category: "grand_prize",
        genre: "novel",
        description: "九州の小さな町で生まれた著者と、故郷を離れ東京で息子を育てたオカンとの母子の愛を綴った半自伝的小説。",
        themes: ["家族", "母子", "人生"],
        amazonKeyword: "東京タワー リリー・フランキー",
      },
      {
        title: "一瞬の風になれ",
        author: "佐藤多佳子",
        year: 2007,
        session: 4,
        category: "grand_prize",
        genre: "novel",
        description: "陸上部を舞台に、主人公と兄、仲間たちの青春と成長を描いた3部作。スプリンターたちの挑戦と友情が熱く燃える。",
        themes: ["青春", "陸上", "友情"],
        amazonKeyword: "一瞬の風になれ 佐藤多佳子",
      },
      {
        title: "ゴールデンスランバー",
        author: "伊坂幸太郎",
        year: 2008,
        session: 5,
        category: "grand_prize",
        genre: "mystery",
        description: "首相暗殺犯に仕立て上げられた男の壮大な逃亡劇。友情と陰謀、過去の記憶が交差するエンターテインメント大作。",
        themes: ["逃亡", "友情", "陰謀"],
        amazonKeyword: "ゴールデンスランバー 伊坂幸太郎",
      },
      {
        title: "告白",
        author: "湊かなえ",
        year: 2009,
        session: 6,
        category: "grand_prize",
        genre: "mystery",
        description: "娘を殺された中学教師が教室で語る復讐の計画。複数の視点が交差するイヤミス傑作。社会問題を鋭く抉り出す問題作。",
        themes: ["復讐", "教師", "社会問題"],
        amazonKeyword: "告白 湊かなえ",
      },
      {
        title: "天地明察",
        author: "冲方丁",
        year: 2010,
        session: 7,
        category: "grand_prize",
        genre: "novel",
        description: "江戸時代に日本初の暦を作り上げた天文暦学者・渋川春海の生涯を描いた歴史小説。真実を追い求める情熱の物語。",
        themes: ["歴史", "天文", "江戸"],
        amazonKeyword: "天地明察 冲方丁",
      },
      {
        title: "謎解きはディナーのあとで",
        author: "東川篤哉",
        year: 2011,
        session: 8,
        category: "grand_prize",
        genre: "mystery",
        description: "お嬢様刑事と毒舌執事のコンビが難事件を解決するユーモアミステリー。軽快な掛け合いと本格謎解きが楽しめる。",
        themes: ["ミステリー", "執事", "ユーモア"],
        amazonKeyword: "謎解きはディナーのあとで 東川篤哉",
      },
      {
        title: "舟を編む",
        author: "三浦しをん",
        year: 2012,
        session: 9,
        category: "grand_prize",
        genre: "novel",
        description: "辞書編集部に配属された不器用な青年が、言葉に向き合いながら成長する物語。辞書作りへの情熱と職人魂を描く。",
        themes: ["辞書", "職人", "言葉"],
        amazonKeyword: "舟を編む 三浦しをん",
      },
      {
        title: "海賊とよばれた男",
        author: "百田尚樹",
        year: 2013,
        session: 10,
        category: "grand_prize",
        genre: "novel",
        description: "出光興産の創業者・出光佐三をモデルに、戦後の石油業界で闘い続けた男の生涯を描いた経済歴史小説。",
        themes: ["歴史", "経営", "石油"],
        amazonKeyword: "海賊とよばれた男 百田尚樹",
      },
      {
        title: "村上海賊の娘",
        author: "和田竜",
        year: 2014,
        session: 11,
        category: "grand_prize",
        genre: "novel",
        description: "戦国時代の瀬戸内海を舞台に、村上海賊の娘・景が織田信長軍と戦う歴史エンターテインメント大作。",
        themes: ["歴史", "戦国", "海賊"],
        amazonKeyword: "村上海賊の娘 和田竜",
      },
      {
        title: "鹿の王",
        author: "上橋菜穂子",
        year: 2015,
        session: 12,
        category: "grand_prize",
        genre: "sf",
        description: "謎の疫病が蔓延するファンタジー世界で、元戦士の男と医師が命をかけて戦う壮大な物語。家族愛と生命の尊さを描く。",
        themes: ["ファンタジー", "疫病", "家族"],
        amazonKeyword: "鹿の王 上橋菜穂子",
      },
      {
        title: "羊と鋼の森",
        author: "宮下奈都",
        year: 2016,
        session: 13,
        category: "grand_prize",
        genre: "novel",
        description: "ピアノ調律師を目指す青年の成長を静かに描いた小説。音楽と職人の世界、音への深い愛情が伝わる清廉な一作。",
        themes: ["音楽", "成長", "職人"],
        amazonKeyword: "羊と鋼の森 宮下奈都",
      },
      {
        title: "みかづき",
        author: "森絵都",
        year: 2017,
        session: 14,
        category: "grand_prize",
        genre: "novel",
        description: "学習塾を舞台に三世代の家族と教育を描いた長編小説。教育とは何かを問いながら、人々の成長と葛藤を丁寧に描く。",
        themes: ["家族", "教育", "塾"],
        amazonKeyword: "みかづき 森絵都",
      },
      {
        title: "かがみの孤城",
        author: "辻村深月",
        year: 2018,
        session: 15,
        category: "grand_prize",
        genre: "novel",
        description: "不登校の少女が鏡の中の城に招かれ、同じ境遇の仲間たちと出会うファンタジー。孤独と繋がりを描いた感動の物語。",
        themes: ["不登校", "友情", "ファンタジー"],
        amazonKeyword: "かがみの孤城 辻村深月",
      },
      {
        title: "そして、バトンは渡された",
        author: "瀬尾まいこ",
        year: 2019,
        session: 16,
        category: "grand_prize",
        genre: "novel",
        description: "複数の親を持つ少女が愛情に包まれて育つ温かい家族小説。血のつながりを超えた愛の形を優しく描いた感動作。",
        themes: ["家族", "継親", "成長"],
        amazonKeyword: "そして、バトンは渡された 瀬尾まいこ",
      },
      {
        title: "流浪の月",
        author: "凪良ゆう",
        year: 2020,
        session: 17,
        category: "grand_prize",
        genre: "novel",
        description: "世間の偏見に晒され続けた二人の再会を描く。傷ついた魂が求める「居場所」と愛の本質を問いかける社会派小説。",
        themes: ["愛", "社会問題", "偏見"],
        amazonKeyword: "流浪の月 凪良ゆう",
      },
      {
        title: "52ヘルツのクジラたち",
        author: "町田そのこ",
        year: 2021,
        session: 18,
        category: "grand_prize",
        genre: "novel",
        description: "虐待サバイバーの女性が、声なき少年と出会い互いに救われていく物語。孤独な魂が繋がる希望と再生の感動作。",
        themes: ["虐待", "孤独", "救済"],
        amazonKeyword: "52ヘルツのクジラたち 町田そのこ",
      },
      {
        title: "赤と青とエスキース",
        author: "青山美智子",
        year: 2022,
        session: 19,
        category: "grand_prize",
        genre: "novel",
        description: "一枚の絵を巡る5つの連作短編。オーストラリアと日本を舞台に、時を超えて人と人が繋がる恋愛と人生の物語。",
        themes: ["恋愛", "人生", "絵画"],
        amazonKeyword: "赤と青とエスキース 青山美智子",
      },
      {
        title: "汝、星のごとく",
        author: "凪良ゆう",
        year: 2023,
        session: 20,
        category: "grand_prize",
        genre: "novel",
        description: "島に生きる男女の切ない恋愛と、それぞれが自分らしく生きることを模索する物語。自由と愛の本質を問いかける傑作。",
        themes: ["恋愛", "生き方", "自由"],
        amazonKeyword: "汝、星のごとく 凪良ゆう",
      },
      {
        title: "成瀬は天下を取りにいく",
        author: "宮島未奈",
        year: 2024,
        session: 21,
        category: "grand_prize",
        genre: "novel",
        description: "滋賀を愛し、独自の哲学で生きる少女・成瀬あかりの青春を描く連作短編。その個性と行動力が笑いと感動を生む。",
        themes: ["青春", "個性", "笑い"],
        amazonKeyword: "成瀬は天下を取りにいく 宮島未奈",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. 直木賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "naoki-sho",
    name: "直木賞",
    officialName: "直木三十五賞",
    description:
      "1935年創設の日本を代表する文学賞。大衆小説の優秀な作品に贈られる。年2回（1月・7月）発表。芥川賞と並ぶ日本最高峰の文学賞として知られる。",
    icon: "🖊️",
    accentColor: "red",
    startYear: 1935,
    frequency: "biannual",
    announcementMonth: 1,
    prestige: "major",
    winners: [
      {
        title: "黒牢城",
        author: "米澤穂信",
        year: 2022,
        session: 166,
        category: "grand_prize",
        genre: "mystery",
        description: "戦国時代、有岡城に幽閉された黒田官兵衛が牢の外で起きる殺人事件を推理する歴史ミステリー傑作。",
        themes: ["歴史", "ミステリー", "戦国"],
        amazonKeyword: "黒牢城 米澤穂信",
      },
      {
        title: "夜に星を放つ",
        author: "窪美澄",
        year: 2022,
        session: 167,
        category: "grand_prize",
        genre: "novel",
        description: "孤独と喪失を抱えた人々が星を頼りに繋がる5篇の連作短編集。現代社会の孤立と心の交流を繊細に描く。",
        themes: ["恋愛", "孤独", "人間関係"],
        amazonKeyword: "夜に星を放つ 窪美澄",
      },
      {
        title: "地図と拳",
        author: "小川哲",
        year: 2023,
        session: 168,
        category: "grand_prize",
        genre: "novel",
        description: "満洲を舞台に、地図作成と都市建設に人生を捧げた男たちの壮大な歴史小説。近代と戦争の狭間で揺れる人間ドラマ。",
        themes: ["歴史", "満洲", "戦争"],
        amazonKeyword: "地図と拳 小川哲",
      },
      {
        title: "しろがねの葉",
        author: "千早茜",
        year: 2023,
        session: 168,
        category: "grand_prize",
        genre: "mystery",
        description: "戦国末期の石見銀山を舞台に、銀山師と生きた女の一生を描く。激動の時代を女の目線で鮮烈に描いた歴史小説。",
        themes: ["歴史", "銀山", "女性"],
        amazonKeyword: "しろがねの葉 千早茜",
      },
      {
        title: "極楽征夷大将軍",
        author: "垣根涼介",
        year: 2023,
        session: 169,
        category: "grand_prize",
        genre: "novel",
        description: "「ぼんくら」と呼ばれた足利尊氏が室町幕府を開くまでの生涯を描く歴史小説。権謀術数渦巻く中世の人間ドラマ。",
        themes: ["歴史", "足利", "武士"],
        amazonKeyword: "極楽征夷大将軍 垣根涼介",
      },
      {
        title: "木挽町のあだ討ち",
        author: "永井紗耶子",
        year: 2023,
        session: 169,
        category: "grand_prize",
        genre: "novel",
        description: "江戸の芝居小屋を舞台に、若侍の仇討ちの真相を複数の証言で解き明かす江戸ミステリー。人情と謎が交わる傑作。",
        themes: ["歴史", "江戸", "仇討ち"],
        amazonKeyword: "木挽町のあだ討ち 永井紗耶子",
      },
      {
        title: "ともぐい",
        author: "河崎秋子",
        year: 2024,
        session: 170,
        category: "grand_prize",
        genre: "novel",
        description: "明治末期の北海道、人喰い熊と対峙するマタギの壮絶な物語。自然と人間の原初的な戦いを圧倒的な筆致で描く。",
        themes: ["自然", "北海道", "生死"],
        amazonKeyword: "ともぐい 河崎秋子",
      },
      {
        title: "八月の御所グラウンド",
        author: "万城目学",
        year: 2024,
        session: 170,
        category: "grand_prize",
        genre: "novel",
        description: "京都の御所グラウンドで繰り広げられる不思議な野球の試合。青春と幻想が交差する万城目ワールド全開の傑作。",
        themes: ["青春", "京都", "野球"],
        amazonKeyword: "八月の御所グラウンド 万城目学",
      },
      {
        title: "ツミデミック",
        author: "一穂ミチ",
        year: 2024,
        session: 171,
        category: "grand_prize",
        genre: "novel",
        description: "コロナ禍という特殊な状況下で罪を犯してしまった人々を描く連作短編集。極限状態の人間の弱さと倫理を問う。",
        themes: ["パンデミック", "罪", "人間関係"],
        amazonKeyword: "ツミデミック 一穂ミチ",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. 芥川賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "akutagawa-sho",
    name: "芥川賞",
    officialName: "芥川龍之介賞",
    description:
      "1935年創設。純文学の新人作家に贈られる日本最高峰の文学賞。年2回（1月・7月）発表。受賞は作家として認められた証とされる。",
    icon: "✒️",
    accentColor: "indigo",
    startYear: 1935,
    frequency: "biannual",
    announcementMonth: 1,
    prestige: "major",
    winners: [
      {
        title: "火花",
        author: "又吉直樹",
        year: 2015,
        session: 153,
        category: "grand_prize",
        genre: "novel",
        description: "お笑い芸人が書いた純文学。若き漫才師が師匠に憧れ芸を磨く青春と挫折の物語。芸の本質と生き方を問う傑作。",
        themes: ["芸人", "青春", "夢"],
        amazonKeyword: "火花 又吉直樹",
      },
      {
        title: "スクラップ・アンド・ビルド",
        author: "羽田圭介",
        year: 2015,
        session: 153,
        category: "grand_prize",
        genre: "novel",
        description: "介護される祖父と向き合う青年の葛藤を描く。老いと死、家族の関係を現代的な視点で問い直す問題作。",
        themes: ["介護", "老い", "家族"],
        amazonKeyword: "スクラップ・アンド・ビルド 羽田圭介",
      },
      {
        title: "異類婚姻譚",
        author: "本谷有希子",
        year: 2016,
        session: 154,
        category: "grand_prize",
        genre: "novel",
        description: "夫婦が互いに溶け合い変容していくシュールな物語。結婚の本質と自己同一性を問うユニークな純文学作品。",
        themes: ["結婚", "夫婦", "変容"],
        amazonKeyword: "異類婚姻譚 本谷有希子",
      },
      {
        title: "死んでいない者",
        author: "滝口悠生",
        year: 2016,
        session: 154,
        category: "grand_prize",
        genre: "novel",
        description: "ある一族の通夜の夜を、生者と死者が混在する独特の時空間で描く。家族と死の記憶が交差する実験的純文学。",
        themes: ["家族", "死", "葬儀"],
        amazonKeyword: "死んでいない者 滝口悠生",
      },
      {
        title: "コンビニ人間",
        author: "村田沙耶香",
        year: 2016,
        session: 155,
        category: "grand_prize",
        genre: "novel",
        description: "18年間コンビニ店員として生きる女性が社会規範に抗う物語。正常と異常の境界を問う現代社会への鋭い批評作。",
        themes: ["コンビニ", "社会", "異質"],
        amazonKeyword: "コンビニ人間 村田沙耶香",
      },
      {
        title: "しんせかい",
        author: "山下澄人",
        year: 2017,
        session: 156,
        category: "grand_prize",
        genre: "novel",
        description: "北海道の演劇塾で過ごした青春時代を独特の文体で描いた自伝的小説。芸術を志す若者の迷いと成長を瑞々しく描く。",
        themes: ["青春", "演劇", "北海道"],
        amazonKeyword: "しんせかい 山下澄人",
      },
      {
        title: "影裏",
        author: "沼田真佑",
        year: 2017,
        session: 157,
        category: "grand_prize",
        genre: "novel",
        description: "岩手に転勤した男が知った友人の二面性と喪失を描く。東日本大震災後の東北を背景にした静謐な心理小説。",
        themes: ["友情", "喪失", "東北"],
        amazonKeyword: "影裏 沼田真佑",
      },
      {
        title: "おらおらでひとりいぐも",
        author: "若竹千佐子",
        year: 2018,
        session: 158,
        category: "grand_prize",
        genre: "novel",
        description: "夫を亡くした74歳の老女が方言混じりの内語で綴る孤独と人生。老いの孤独と自由を温かくユーモラスに描く。",
        themes: ["孤独", "老い", "方言"],
        amazonKeyword: "おらおらでひとりいぐも 若竹千佐子",
      },
      {
        title: "むらさきのスカートの女",
        author: "今村夏子",
        year: 2019,
        session: 161,
        category: "grand_prize",
        genre: "novel",
        description: "近所の「むらさきのスカートの女」を観察し続ける語り手が徐々に異様な存在感を帯びる。日常に潜む恐怖と孤独を描く。",
        themes: ["ストーカー", "日常", "不気味"],
        amazonKeyword: "むらさきのスカートの女 今村夏子",
      },
      {
        title: "貝に続く場所にて",
        author: "石沢麻依",
        year: 2021,
        session: 165,
        category: "grand_prize",
        genre: "novel",
        description: "ドイツの古都ゲッティンゲンで、東日本大震災で亡くなった友人の幻と再会する幻想的な物語。記憶と喪失を描く。",
        themes: ["震災", "幻想", "記憶"],
        amazonKeyword: "貝に続く場所にて 石沢麻依",
      },
      {
        title: "彼岸花が咲く島",
        author: "李琴峰",
        year: 2021,
        session: 165,
        category: "grand_prize",
        genre: "novel",
        description: "謎の島に流れ着いた少女が言語と文化の異なる共同体で生きる物語。言語と女性、アイデンティティを問う問題作。",
        themes: ["言語", "島", "女性"],
        amazonKeyword: "彼岸花が咲く島 李琴峰",
      },
      {
        title: "ブラックボックス",
        author: "砂川文次",
        year: 2022,
        session: 166,
        category: "grand_prize",
        genre: "novel",
        description: "自衛隊経験を持つ男が自転車便の仕事中に暴力事件を起こす物語。社会の周縁を生きる男の暴力と孤立を描く。",
        themes: ["暴力", "社会", "自衛隊"],
        amazonKeyword: "ブラックボックス 砂川文次",
      },
      {
        title: "おいしいごはんが食べられますように",
        author: "高瀬隼子",
        year: 2022,
        session: 167,
        category: "grand_prize",
        genre: "novel",
        description: "職場の食事をめぐる人間関係の微妙な緊張を描く。食という行為を通して現代の職場の息苦しさと人間模様を鋭く映す。",
        themes: ["職場", "食事", "人間関係"],
        amazonKeyword: "おいしいごはんが食べられますように 高瀬隼子",
      },
      {
        title: "この世の喜びよ",
        author: "井戸川射子",
        year: 2023,
        session: 168,
        category: "grand_prize",
        genre: "novel",
        description: "ショッピングモールの喪服売り場で働く女性が過去の記憶と向き合う詩的な物語。日常の細部に宿る生の喜びを描く。",
        themes: ["母子", "記憶", "日常"],
        amazonKeyword: "この世の喜びよ 井戸川射子",
      },
      {
        title: "荒地の家族",
        author: "佐藤厚志",
        year: 2023,
        session: 168,
        category: "grand_prize",
        genre: "novel",
        description: "東日本大震災後の宮城県で、家族を失った植木職人の再生を描く。震災後の喪失と生きることへの意志を綴る純文学。",
        themes: ["震災", "家族", "復興"],
        amazonKeyword: "荒地の家族 佐藤厚志",
      },
      {
        title: "ハンチバック",
        author: "市川沙央",
        year: 2023,
        session: 169,
        category: "grand_prize",
        genre: "novel",
        description: "重度障害を持つ女性が書いた衝撃の問題作。障害者の性と尊厳、社会の偏見を真正面から描いた芥川賞史上最大の話題作。",
        themes: ["障害", "社会問題", "文学"],
        amazonKeyword: "ハンチバック 市川沙央",
      },
      {
        title: "東京都同情塔",
        author: "九段理江",
        year: 2024,
        session: 170,
        category: "grand_prize",
        genre: "novel",
        description: "AI生成文章を含む実験的構成で、新宿に建設される「同情塔」を巡る近未来の物語。AIと人間の言語の境界を問う。",
        themes: ["建築", "AI", "社会"],
        amazonKeyword: "東京都同情塔 九段理江",
      },
      {
        title: "サンショウウオの四十九日",
        author: "朝比奈秋",
        year: 2024,
        session: 171,
        category: "grand_prize",
        genre: "novel",
        description: "一つの体に二つの意識を持つ結合双生児の姉妹の物語。生と死、自己と他者の境界を問う哲学的な純文学作品。",
        themes: ["双子", "死", "生命"],
        amazonKeyword: "サンショウウオの四十九日 朝比奈秋",
      },
      {
        title: "バリ山行",
        author: "松永K三蔵",
        year: 2024,
        session: 171,
        category: "grand_prize",
        genre: "novel",
        description: "会社員が先輩に誘われてバリエーションルート登山に挑む物語。職場の人間関係と山という舞台で人生の本質を問う。",
        themes: ["登山", "職場", "人生"],
        amazonKeyword: "バリ山行 松永K三蔵",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. このミステリーがすごい!
  // ─────────────────────────────────────────────────────────────
  {
    id: "kono-mystery",
    name: "このミステリーがすごい!",
    description:
      "宝島社が毎年12月に発表するミステリランキング。国内外のミステリ作家・評論家・書店員が投票して決定する。国内1位は「このミス大賞」と並ぶミステリ界最大の栄誉。",
    icon: "🔍",
    accentColor: "blue",
    startYear: 1988,
    frequency: "annual",
    announcementMonth: 12,
    prestige: "major",
    winners: [
      {
        title: "屍人荘の殺人",
        author: "今村昌弘",
        year: 2018,
        category: "grand_prize",
        genre: "mystery",
        description: "合宿所がゾンビに包囲されクローズドサークルとなる奇抜な設定の本格ミステリ。鮮やかな謎解きと驚愕のトリックが話題に。",
        themes: ["ミステリー", "クローズドサークル", "ゾンビ"],
        amazonKeyword: "屍人荘の殺人 今村昌弘",
      },
      {
        title: "medium 霊媒探偵城塚翡翠",
        author: "相沢沙呼",
        year: 2021,
        category: "grand_prize",
        genre: "mystery",
        description: "霊媒師の美女と推理作家が難事件を解決する本格ミステリ。終盤の驚愕の展開が読者を震撼させた2020年最大の話題作。",
        themes: ["霊媒", "探偵", "トリック"],
        amazonKeyword: "medium 霊媒探偵城塚翡翠 相沢沙呼",
      },
      {
        title: "黒牢城",
        author: "米澤穂信",
        year: 2022,
        category: "grand_prize",
        genre: "mystery",
        description: "戦国時代、有岡城に幽閉された黒田官兵衛が牢の外で起きる殺人事件を推理する歴史ミステリー傑作。直木賞も受賞。",
        themes: ["歴史", "ミステリー", "戦国"],
        amazonKeyword: "黒牢城 米澤穂信",
      },
      {
        title: "爆弾",
        author: "呉勝浩",
        year: 2023,
        category: "grand_prize",
        genre: "mystery",
        description: "爆弾予告犯と刑事の心理戦を描いた緊迫のクライムサスペンス。読者を引き込む圧倒的な緊張感と意外な結末が話題。",
        themes: ["爆弾", "犯罪", "心理"],
        amazonKeyword: "爆弾 呉勝浩",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. キノベス!
  // ─────────────────────────────────────────────────────────────
  {
    id: "kinobesu",
    name: "キノベス!",
    officialName: "キノベス!",
    description:
      "紀伊國屋書店のスタッフが選ぶ年間ベスト本ランキング。2012年スタート。現場で本を売る書店員の目線から選ばれる信頼度の高いランキング。",
    icon: "🏷️",
    accentColor: "green",
    startYear: 2012,
    frequency: "annual",
    announcementMonth: 1,
    prestige: "major",
    winners: [
      {
        title: "君の膵臓をたべたい",
        author: "住野よる",
        year: 2016,
        category: "grand_prize",
        genre: "novel",
        description: "余命わずかな少女と「僕」の交流を描いた青春小説。タイトルの意味が明かされるラストに多くの読者が涙した。",
        themes: ["青春", "病気", "友情"],
        amazonKeyword: "君の膵臓をたべたい 住野よる",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 6. 本格ミステリ大賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "honkaku-mystery",
    name: "本格ミステリ大賞",
    description:
      "本格ミステリ作家クラブが2001年から毎年授与する賞。小説部門と評論・研究部門がある。本格ミステリの発展に貢献した作品を顕彰する。",
    icon: "🕵️",
    accentColor: "purple",
    startYear: 2001,
    frequency: "annual",
    announcementMonth: 5,
    prestige: "notable",
    winners: [
      {
        title: "屍人荘の殺人",
        author: "今村昌弘",
        year: 2018,
        category: "grand_prize",
        genre: "mystery",
        description: "ゾンビに包囲された合宿所を舞台にしたクローズドサークル本格ミステリ。鮮やかなトリックと伏線が高く評価された。",
        themes: ["ミステリー", "本格", "クローズドサークル"],
        amazonKeyword: "屍人荘の殺人 今村昌弘",
      },
      {
        title: "元年春之祭",
        author: "陸秋槎",
        year: 2019,
        category: "grand_prize",
        genre: "mystery",
        description: "中国の戦国時代を舞台にした本格ミステリ。古代中国の文化と論理パズル的謎解きを融合させた意欲作。",
        themes: ["ミステリー", "本格", "中国"],
        amazonKeyword: "元年春之祭 陸秋槎",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 7. 吉川英治文学新人賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "yoshikawa-shinjin",
    name: "吉川英治文学新人賞",
    officialName: "吉川英治文学新人賞",
    description:
      "1980年創設。新進作家の優れた大衆小説に贈られる賞。吉川英治文化振興財団が主催し、毎年3月頃発表。次世代の文学者を発掘する登竜門的な賞。",
    icon: "🌱",
    accentColor: "emerald",
    startYear: 1980,
    frequency: "annual",
    announcementMonth: 3,
    prestige: "notable",
    winners: [
      {
        title: "テスカトリポカ",
        author: "佐藤究",
        year: 2022,
        category: "grand_prize",
        genre: "novel",
        description: "メキシコの麻薬カルテルと日本の闇社会が交わる国際犯罪小説。アステカ神話を背景にした圧倒的スケールの暗黒小説。",
        themes: ["犯罪", "麻薬", "国際"],
        amazonKeyword: "テスカトリポカ 佐藤究",
      },
      {
        title: "地図と拳",
        author: "小川哲",
        year: 2023,
        category: "grand_prize",
        genre: "novel",
        description: "満洲を舞台にした壮大な歴史小説。直木賞も受賞した注目作。地図と都市建設を通して近代日本の野望と挫折を描く。",
        themes: ["歴史", "満洲", "戦争"],
        amazonKeyword: "地図と拳 小川哲",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 8. 山本周五郎賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "yamamoto-shugoro",
    name: "山本周五郎賞",
    officialName: "山本周五郎賞",
    description:
      "1988年創設。優れた物語性を持つ小説に贈られる。新潮社が主催し毎年5月頃発表。人間を深く描いた物語を顕彰する賞として知られる。",
    icon: "📖",
    accentColor: "orange",
    startYear: 1988,
    frequency: "annual",
    announcementMonth: 5,
    prestige: "notable",
    winners: [
      {
        title: "流浪の月",
        author: "凪良ゆう",
        year: 2020,
        category: "grand_prize",
        genre: "novel",
        description: "世間から誤解され続けた二人の人間が求める真の居場所を描く。本屋大賞も受賞した社会派ラブストーリーの傑作。",
        themes: ["愛", "偏見", "社会問題"],
        amazonKeyword: "流浪の月 凪良ゆう",
      },
      {
        title: "黒牢城",
        author: "米澤穂信",
        year: 2022,
        category: "grand_prize",
        genre: "mystery",
        description: "戦国時代を舞台にした歴史ミステリの傑作。直木賞・このミス1位なども受賞し、各方面で高く評価された話題作。",
        themes: ["歴史", "ミステリー", "戦国"],
        amazonKeyword: "黒牢城 米澤穂信",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 9. 日本SF大賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "nihon-sf",
    name: "日本SF大賞",
    officialName: "日本SF大賞",
    description:
      "日本SF作家クラブが1980年から毎年授与する賞。国内で発表されたSF作品の中から最も優れた作品を選出。日本SFの最高峰とされる権威ある賞。",
    icon: "🚀",
    accentColor: "cyan",
    startYear: 1980,
    frequency: "annual",
    announcementMonth: 12,
    prestige: "notable",
    winners: [
      // TODO: verify specific recent winners with confidence
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 10. マンガ大賞
  // ─────────────────────────────────────────────────────────────
  {
    id: "manga-taisho",
    name: "マンガ大賞",
    officialName: "マンガ大賞",
    description:
      "2008年創設。書店員など本のプロが「一番好きなマンガ」を選ぶ賞。毎年3月頃発表。単行本1〜8巻までの作品が対象で、本屋大賞のマンガ版とも称される。",
    icon: "🎌",
    accentColor: "pink",
    startYear: 2008,
    frequency: "annual",
    announcementMonth: 3,
    prestige: "notable",
    winners: [
      {
        title: "ダンジョン飯",
        author: "九井諒子",
        year: 2017,
        category: "grand_prize",
        genre: "manga",
        description: "ダンジョンの魔物を食料にしながら進む探索者たちのグルメファンタジー。独自の設定と食の描写が絶賛された傑作。",
        themes: ["ファンタジー", "料理", "冒険"],
        amazonKeyword: "ダンジョン飯 九井諒子",
      },
      {
        title: "ゴールデンカムイ",
        author: "野田サトル",
        year: 2018,
        category: "grand_prize",
        genre: "manga",
        description: "明治末期の北海道を舞台に、アイヌの金塊を巡る争奪戦を描く。アイヌ文化の描写と緻密なサバイバルが魅力の大作。",
        themes: ["歴史", "北海道", "アイヌ"],
        amazonKeyword: "ゴールデンカムイ 野田サトル",
      },
      {
        title: "ブルーピリオド",
        author: "山口つばさ",
        year: 2019,
        category: "grand_prize",
        genre: "manga",
        description: "美術と無縁だった高校生が東京藝術大学を目指す受験青春漫画。アートの魅力と青春の苦悩を描いた感動的な作品。",
        themes: ["青春", "美術", "受験"],
        amazonKeyword: "ブルーピリオド 山口つばさ",
      },
      {
        title: "スキップとローファー",
        author: "高松美咲",
        year: 2023,
        category: "grand_prize",
        genre: "manga",
        description: "地方出身の女の子が上京して東京の高校に通う青春漫画。人との関係を通じて成長する主人公の姿が温かく描かれる。",
        themes: ["青春", "上京", "友情"],
        amazonKeyword: "スキップとローファー 高松美咲",
      },
      {
        title: "【推しの子】",
        author: "赤坂アカ×横槍メンゴ",
        year: 2024,
        category: "grand_prize",
        genre: "manga",
        description: "芸能界の光と影を描いたダークファンタジー。転生した産婦人科医が芸能界で母の復讐を誓う衝撃的な展開が話題。",
        themes: ["芸能", "復讐", "青春"],
        amazonKeyword: "推しの子 赤坂アカ 横槍メンゴ",
      },
    ],
  },
];
