/**
 * add-novels-100.ts
 *
 * 小説100作品をbooks.index.jsonとsummaries-supplement.jsonに追加するスクリプト。
 * T-1101対応。
 *
 * Usage: npx tsx scripts/add-novels-100.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

// ── WorkId生成ロジック（normalize-works.tsと同じ） ──────────────────
function normalizeTitle(s: string): string {
  return s
    .toLowerCase()
    .replace(/[Ａ-Ｚａ-ｚ０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0))
    .replace(/　/g, " ")
    .replace(/[・‐－\-～〜]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function makeWorkId(type: string, baseTitle: string, firstAuthor: string): string {
  const normalBase = normalizeTitle(baseTitle)
    .replace(/[^\w\u3040-\u30ff\u4e00-\u9fff\u3400-\u4dbf]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .substring(0, 40);
  const authorSlug = firstAuthor
    .replace(/[^\w\u3040-\u30ff\u4e00-\u9fff]/g, "")
    .substring(0, 10);
  return `${type}__${normalBase}__${authorSlug}`.toLowerCase();
}

// ── 小説データ定義 ──────────────────────────────────────────────────

interface NovelEntry {
  title: string;
  author: string;
  category: string; // books.index.jsonのcategories用
  l1Id: string;
  l2Id: string;
  l3Id: string;
  publishedDate: string;
  pageCount?: number;
  publisher?: string;
  summaryShort: string;
  moodTags?: {
    emotionalTags?: string[];
    purposeTags?: string[];
    atmosphereTags?: string[];
    paceTag?: string;
    depthTag?: string;
    readingEaseTag?: string;
    completionStatus?: string;
    estimatedReadingTimeCategory?: string;
    recommendationCatch?: string;
    recommendedFor?: string[];
  };
}

const novels: NovelEntry[] = [
  // ═══════════════════════════════════════════════════════════════════
  // SF小説（15作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "アンドロイドは電気羊の夢を見るか？",
    author: "フィリップ・K・ディック",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "ai-tech-sf",
    publishedDate: "1969",
    pageCount: 336,
    publisher: "早川書房",
    summaryShort: "核戦争後の荒廃した地球を舞台に、人造人間を狩る賞金稼ぎリック・デッカードの物語。人間とアンドロイドの境界を問いかけるフィリップ・K・ディックの最高傑作。映画『ブレードランナー』の原作としても名高く、SFファンはもちろん「人間とは何か」を考えたい人におすすめの一冊。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["dark", "extraordinary"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "人間とは何かを問うSF金字塔",
      recommendedFor: ["SF好き", "哲学的テーマが好きな人", "映画原作に興味がある人"],
    },
  },
  {
    title: "ユービック",
    author: "フィリップ・K・ディック",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "ai-tech-sf",
    publishedDate: "1978",
    pageCount: 304,
    publisher: "早川書房",
    summaryShort: "現実と虚構の境界が崩壊していく恐怖を描いたフィリップ・K・ディックの傑作SF。超能力者が暗躍する近未来で、主人公たちは次々と不可解な現象に巻き込まれる。「現実とは何か」という根源的な問いを突きつけるディック文学の真骨頂。SF好きも哲学好きも唸らせる必読の一冊。",
    moodTags: {
      emotionalTags: ["scary"],
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["uneasy", "extraordinary"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "現実崩壊の恐怖を描くディック最高傑作の一つ",
      recommendedFor: ["SF好き", "哲学的テーマが好きな人"],
    },
  },
  {
    title: "高い城の男",
    author: "フィリップ・K・ディック",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "1984",
    pageCount: 320,
    publisher: "早川書房",
    summaryShort: "第二次世界大戦で枢軸国側が勝利した世界を描く歴史改変SFの金字塔。日本とドイツに分割統治されたアメリカで、人々は「もう一つの歴史」を記した禁書に導かれる。ヒューゴー賞受賞作であり、ディックの代表作の一つ。歴史好き・SF好きの双方におすすめ。",
    moodTags: {
      purposeTags: ["thinking", "intellectual", "immersive"],
      atmosphereTags: ["uneasy", "extraordinary"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "もし枢軸国が勝っていたら？歴史改変SFの名作",
      recommendedFor: ["SF好き", "歴史好き", "ディストピア小説が好きな人"],
    },
  },
  {
    title: "虐殺器官",
    author: "伊藤計劃",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "2007-06",
    pageCount: 320,
    publisher: "早川書房",
    summaryShort: "9.11後のテロとの戦いが激化した近未来を舞台に、世界各地の虐殺を引き起こす謎の男を追う米軍特殊部隊員の物語。言語と暴力、テクノロジーと倫理を鋭く問う伊藤計劃のデビュー作。圧倒的なリアリティと思弁性を兼ね備えた、21世紀日本SFの最高傑作の一つ。ハードSFや軍事SFが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot"],
      purposeTags: ["thinking", "intellectual", "immersive"],
      atmosphereTags: ["dark", "tense", "extraordinary"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "言語が虐殺を生む？衝撃の近未来SF",
      recommendedFor: ["ハードSF好き", "社会派SF好き", "軍事SF好き"],
    },
  },
  {
    title: "ハーモニー",
    author: "伊藤計劃",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "dystopia",
    publishedDate: "2008-12",
    pageCount: 352,
    publisher: "早川書房",
    summaryShort: "医療技術が極限まで発達し、すべての人が健康を管理される「優しいディストピア」を描く伊藤計劃の遺作的傑作。完璧な社会に違和感を抱く少女たちの反乱と、人間の意識の本質に迫るSF。フィリップ・K・ディック賞特別賞受賞。管理社会やユートピア/ディストピアに興味がある人におすすめ。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["calm", "extraordinary"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "優しさが支配する世界の恐怖を描くディストピアSF",
      recommendedFor: ["ディストピア好き", "伊藤計劃ファン", "哲学的SF好き"],
    },
  },
  {
    title: "三体",
    author: "劉慈欣",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "space-sf",
    publishedDate: "2019-07",
    pageCount: 424,
    publisher: "早川書房",
    summaryShort: "文化大革命を発端に、異星文明との接触が人類の運命を左右する壮大なSF三部作の第一巻。中国発のヒューゴー賞受賞作であり、物理学の難問「三体問題」をモチーフにしたスケール感は圧倒的。科学と歴史、宇宙と文明が交差するハードSFの新たな金字塔。壮大な宇宙SFが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot"],
      purposeTags: ["thinking", "intellectual", "immersive"],
      atmosphereTags: ["extraordinary", "tense"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "異星文明と人類の壮大な対峙を描く宇宙SF",
      recommendedFor: ["ハードSF好き", "宇宙SF好き", "壮大な物語が好きな人"],
    },
  },
  {
    title: "幼年期の終わり",
    author: "アーサー・C・クラーク",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "space-sf",
    publishedDate: "1979",
    pageCount: 304,
    publisher: "早川書房",
    summaryShort: "突如地球に現れた異星人「オーバーロード」によって平和と繁栄がもたらされた人類。しかしその真の目的は人類の想像を超えるものだった。アーサー・C・クラークが描く人類進化の壮大なビジョンは、SFファンを半世紀以上にわたって魅了し続けている。宇宙と人類の未来に思いを馳せたい人におすすめ。",
    moodTags: {
      emotionalTags: ["emotional", "sad"],
      purposeTags: ["thinking", "intellectual", "immersive"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "人類の進化と終焉を描くSFの古典的名作",
      recommendedFor: ["宇宙SF好き", "哲学的SF好き", "古典SF入門に"],
    },
  },
  {
    title: "一九八四年",
    author: "ジョージ・オーウェル",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "dystopia",
    publishedDate: "2009-07",
    pageCount: 512,
    publisher: "早川書房",
    summaryShort: "全体主義国家オセアニアで「ビッグ・ブラザー」に監視される社会を描いたディストピア文学の金字塔。思想統制・言語操作・歴史改竄といったテーマは現代にも鋭く突き刺さる。ジョージ・オーウェルの代表作であり、文学史に燦然と輝く必読書。監視社会や自由について考えたい人におすすめ。",
    moodTags: {
      emotionalTags: ["hopeless"],
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["dark", "uneasy"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "全体主義の恐怖を描く不朽のディストピア文学",
      recommendedFor: ["ディストピア好き", "社会派小説好き", "古典文学好き"],
    },
  },
  {
    title: "華氏451度",
    author: "レイ・ブラッドベリ",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "dystopia",
    publishedDate: "2014-01",
    pageCount: 272,
    publisher: "早川書房",
    summaryShort: "本を読むことが禁じられ、書物を焼却する「焚書官」が存在する未来社会を描くレイ・ブラッドベリの代表作。華氏451度は紙が自然発火する温度。知識と自由が奪われた世界で、一人の男が目覚めていく物語は今なお普遍的な警告を発している。読書の意味を問い直したい人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "sad"],
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["dark", "extraordinary"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "本を焼く社会が問う、読書と自由の意味",
      recommendedFor: ["ディストピア好き", "本好きの人", "SF入門に"],
    },
  },
  {
    title: "ソラリス",
    author: "スタニスワフ・レム",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "space-sf",
    publishedDate: "2015-04",
    pageCount: 448,
    publisher: "早川書房",
    summaryShort: "知性を持つ海に覆われた惑星ソラリスを調査する科学者たちが、自らの記憶から生み出された存在と対峙する。スタニスワフ・レムが描く「真に異質な知性」との遭遇は、人間の認識の限界を鋭く突く。哲学的SF文学の最高峰であり、ハードSFと文学性を兼ね備えた傑作。深い思索を楽しみたい人におすすめ。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking", "intellectual", "immersive"],
      atmosphereTags: ["calm", "extraordinary", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "異質な知性との遭遇を描く哲学的SF",
      recommendedFor: ["哲学的SF好き", "ハードSF好き", "文学的SF好き"],
    },
  },
  {
    title: "新世界より",
    author: "貴志祐介",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "dystopia",
    publishedDate: "2008-01",
    pageCount: 608,
    publisher: "講談社",
    summaryShort: "1000年後の日本、念動力（呪力）を持つ人類が暮らす一見穏やかな社会の裏に潜む恐るべき秘密を描く貴志祐介の大作SF。日本SF大賞受賞。少年少女の成長物語と壮大な世界観構築が見事に融合した、読後に世界の見え方が変わるディストピア小説。壮大な物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["scary", "emotional"],
      purposeTags: ["thinking", "immersive", "binge"],
      atmosphereTags: ["dark", "extraordinary", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "呪力社会に隠された衝撃の真実を描くディストピアSF",
      recommendedFor: ["ディストピア好き", "日本SF好き", "壮大な物語好き"],
    },
  },
  {
    title: "All You Need Is Kill",
    author: "桜坂洋",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "2004-12",
    pageCount: 224,
    publisher: "集英社",
    summaryShort: "異星生物との戦争でタイムループに囚われた新兵が、死と再生を繰り返しながら最強の兵士へと成長していく。桜坂洋によるライトノベル発のSFアクション小説。ハリウッド映画『オール・ユー・ニード・イズ・キル』の原作。テンポよく一気に読める爽快なSFアクションが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "refreshing"],
      purposeTags: ["binge", "easy"],
      atmosphereTags: ["tense", "extraordinary"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "ループする戦場で最強を目指すSFアクション",
      recommendedFor: ["アクション好き", "SF入門に", "映画原作好き"],
    },
  },
  {
    title: "星を継ぐもの",
    author: "ジェイムズ・P・ホーガン",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "hard-sf",
    publishedDate: "1980-05",
    pageCount: 304,
    publisher: "東京創元社",
    summaryShort: "月面で発見された5万年前の宇宙服を着た人間の死体。この謎の解明に挑む科学者たちの知的興奮を描いたハードSFの傑作。科学的推理の面白さと壮大な謎が見事に融合し、読後の爽快感は格別。SF初心者にも読みやすく、ハードSF入門書として最適な一冊。知的好奇心を刺激されたい人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing"],
      purposeTags: ["thinking", "intellectual", "binge"],
      atmosphereTags: ["extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "月面の謎を科学で解き明かすハードSFの名作",
      recommendedFor: ["ハードSF好き", "SF入門に", "知的好奇心旺盛な人"],
    },
  },
  {
    title: "夏への扉",
    author: "ロバート・A・ハインライン",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "2010-01",
    pageCount: 320,
    publisher: "早川書房",
    summaryShort: "恋人と親友に裏切られた発明家が、愛猫ピートとともにタイムトラベルで人生をやり直す物語。ロバート・A・ハインラインによるSFロマンスの古典であり、温かみのある読後感が多くの読者に愛されている。SF入門書としても最適で、前向きな気持ちになれるタイムトラベル小説を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing", "positive"],
      purposeTags: ["easy", "binge"],
      atmosphereTags: ["bright"],
      paceTag: "普通", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "猫と一緒にやり直す、温かなタイムトラベルSF",
      recommendedFor: ["SF入門に", "猫好き", "前向きな物語が好きな人"],
    },
  },
  {
    title: "タイタンの妖女",
    author: "カート・ヴォネガット",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "space-sf",
    publishedDate: "2009-02",
    pageCount: 384,
    publisher: "早川書房",
    summaryShort: "火星から土星の衛星タイタンまで、壮大な宇宙を舞台に人類の運命と自由意志の虚しさを描くカート・ヴォネガットの傑作SF。ブラックユーモアと哲学的洞察に満ちた作品で、「人生の意味とは何か」を問いかける。独特の文体とシニカルな世界観が癖になる、文学的SF好きにおすすめの一冊。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["extraordinary"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "人生の意味を問うヴォネガットの宇宙SF",
      recommendedFor: ["文学的SF好き", "ブラックユーモア好き", "哲学好き"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // ファンタジー小説（15作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "月の影 影の海",
    author: "小野不由美",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2012-06",
    pageCount: 576,
    publisher: "新潮社",
    summaryShort: "異世界「十二国」に突然放り込まれた女子高生・陽子が、過酷な運命に立ち向かいながら自らの使命を見出していく壮大な和風ファンタジー。小野不由美が構築した精緻な世界観と、陽子の成長物語は圧巻。十二国記シリーズの入口であり、本格ファンタジーが好きな人におすすめの名作。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["extraordinary", "tense"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "異世界で王となる少女の壮大な成長物語",
      recommendedFor: ["和風ファンタジー好き", "成長物語好き", "本格ファンタジー入門に"],
    },
  },
  {
    title: "精霊の守り人",
    author: "上橋菜穂子",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2007-03",
    pageCount: 320,
    publisher: "新潮社",
    summaryShort: "女用心棒バルサが皇子チャグムを守り、精霊の卵をめぐる陰謀と戦う冒険ファンタジー。上橋菜穂子が描く緻密な異世界の文化・風俗は人類学的な深みを持ち、大人の鑑賞に耐える本格ファンタジーとして高い評価を受ける。守り人シリーズの第一作であり、骨太な物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["extraordinary", "tense"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "女用心棒が皇子を守る本格冒険ファンタジー",
      recommendedFor: ["本格ファンタジー好き", "骨太な物語好き", "守り人シリーズ入門に"],
    },
  },
  {
    title: "獣の奏者",
    author: "上橋菜穂子",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2009-08",
    pageCount: 336,
    publisher: "講談社",
    summaryShort: "闘蛇を操る母を失った少女エリンが、王獣と呼ばれる神秘的な生き物と心を通わせながら、国の運命を揺るがす真実に近づいていく。上橋菜穂子が描く人と獣の絆の物語は、生態学的リアリティと深い感動に満ちている。自然や動物への畏敬の念を感じたい人におすすめの本格ファンタジー。",
    moodTags: {
      emotionalTags: ["emotional", "hot"],
      purposeTags: ["immersive", "thinking"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "少女と王獣の絆が国の運命を変える壮大な物語",
      recommendedFor: ["本格ファンタジー好き", "動物好き", "上橋菜穂子ファン"],
    },
  },
  {
    title: "指輪物語 旅の仲間",
    author: "J.R.R.トールキン",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "1992-05",
    pageCount: 624,
    publisher: "評論社",
    summaryShort: "冥王サウロンの「一つの指輪」を滅ぼすため、ホビットのフロドと仲間たちが壮大な旅に出る。J.R.R.トールキンが創造した中つ国の世界は、現代ファンタジーの原点にして頂点。映画でも知られる不朽の名作であり、壮大な冒険ファンタジーの原体験を求める人に必読の一冊。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "すべてのファンタジーの原点にして頂点",
      recommendedFor: ["ファンタジー好き", "冒険物語好き", "映画ファン"],
    },
  },
  {
    title: "ハリー・ポッターと賢者の石",
    author: "J.K.ローリング",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "1999-12",
    pageCount: 464,
    publisher: "静山社",
    summaryShort: "孤独な少年ハリーが魔法学校ホグワーツに入学し、魔法の世界で友情と冒険を経験する。J.K.ローリングが描く魔法世界は緻密で魅力的、子どもから大人まで夢中にさせる世界的ベストセラーシリーズの第一巻。ファンタジー入門にも最適で、冒険と友情の物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing", "emotional"],
      purposeTags: ["immersive", "binge", "easy"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "魔法学校で始まる冒険と友情の物語",
      recommendedFor: ["ファンタジー入門に", "冒険好き", "全年齢"],
    },
  },
  {
    title: "ゲド戦記 影との戦い",
    author: "アーシュラ・K・ル＝グウィン",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2009-01",
    pageCount: 288,
    publisher: "岩波書店",
    summaryShort: "魔法使いの少年ゲドが、自らの影と対峙しながら成長していくファンタジーの古典。アーシュラ・K・ル＝グウィンが描くアースシー世界は、深い哲学と詩的な美しさに満ちている。善と悪、光と影のバランスをテーマにした物語は、年齢を問わず心に響く。哲学的なファンタジーが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["emotional"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "自らの影と対峙する魔法使いの成長物語",
      recommendedFor: ["本格ファンタジー好き", "哲学好き", "ル＝グウィンファン"],
    },
  },
  {
    title: "ナルニア国物語 ライオンと魔女",
    author: "C.S.ルイス",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2000-06",
    pageCount: 224,
    publisher: "岩波書店",
    summaryShort: "衣装ダンスの奥に広がる魔法の国ナルニアで、4人の兄弟姉妹が偉大なライオン・アスランとともに白い魔女に立ち向かう冒険物語。C.S.ルイスの古典的名作であり、子どもの読書体験の原点ともいえる作品。冒険と勇気、善と悪の戦いを楽しみたい人におすすめのファンタジー。",
    moodTags: {
      emotionalTags: ["refreshing", "hot"],
      purposeTags: ["immersive", "easy"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "衣装ダンスの奥に広がる魔法の国の冒険",
      recommendedFor: ["ファンタジー入門に", "冒険好き", "児童文学好き"],
    },
  },
  {
    title: "鹿の王",
    author: "上橋菜穂子",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2014-09",
    pageCount: 576,
    publisher: "KADOKAWA",
    summaryShort: "謎の疫病から生き延びた戦士ヴァンと、その治療法を追う医師ホッサルの物語。上橋菜穂子が本屋大賞を受賞した医療ファンタジーであり、疫病・免疫・民族対立という現代的テーマを異世界に投影した傑作。命とは何かを問いかける、大人のためのファンタジー小説を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["emotional", "hot"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "疫病と命をテーマにした本格医療ファンタジー",
      recommendedFor: ["上橋菜穂子ファン", "本格ファンタジー好き", "医療テーマに興味がある人"],
    },
  },
  {
    title: "ブレイブ・ストーリー",
    author: "宮部みゆき",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2006-05",
    pageCount: 832,
    publisher: "角川書店",
    summaryShort: "家庭崩壊に悩む小学5年生のワタルが、運命を変えるため異世界「幻界」に旅立つ冒険ファンタジー。宮部みゆきが描く少年の成長と冒険は、ゲーム的な世界観と深い人間ドラマが融合した大作。子どもから大人まで楽しめる、感動的なファンタジー冒険小説を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "少年が異世界で運命を変える冒険ファンタジー",
      recommendedFor: ["冒険ファンタジー好き", "宮部みゆきファン", "感動作品好き"],
    },
  },
  {
    title: "図書館の魔女",
    author: "高田大介",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2013-01",
    pageCount: 744,
    publisher: "講談社",
    summaryShort: "言葉を操る力を持つ盲目の少女マツリカと、彼女の護衛に選ばれた少年キリヒトの物語。高田大介が描く「言語」をテーマにした知的ファンタジーは、政治・外交・言語学が複雑に絡み合う壮大な世界を展開する。知的好奇心を刺激される本格ファンタジーが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot"],
      purposeTags: ["thinking", "intellectual", "immersive"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "言語を武器に戦う知的ファンタジーの大作",
      recommendedFor: ["知的ファンタジー好き", "言語学に興味がある人", "重厚な物語好き"],
    },
  },
  {
    title: "鏡の孤城",
    author: "辻村深月",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2017-05",
    pageCount: 560,
    publisher: "ポプラ社",
    summaryShort: "学校に行けなくなった中学生の少女が、光る鏡を通じて不思議な城に招かれる。そこには同じ境遇の7人の少年少女が集まっていた。辻村深月が本屋大賞を受賞したファンタジーミステリーであり、不登校という現代的テーマと見事な伏線回収が話題に。生きづらさを感じている人に届けたい感動作。",
    moodTags: {
      emotionalTags: ["emotional", "heartwarming"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["gentle", "extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "不登校の少年少女が集う鏡の城の秘密",
      recommendedFor: ["感動作品好き", "伏線回収好き", "辻村深月ファン"],
    },
  },
  {
    title: "後宮の烏",
    author: "白川紺子",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2018-04",
    pageCount: 304,
    publisher: "集英社",
    summaryShort: "中華風の架空王朝を舞台に、後宮の奥深くに住む不思議な妃「烏妃」が怪異や事件を解決する和風・中華ファンタジー。美しい世界観と妖しい雰囲気、そして切ないラブストーリーが魅力。アニメ化もされた人気シリーズ第一巻。後宮ものや中華ファンタジーが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["sad", "heartwarming"],
      purposeTags: ["immersive"],
      atmosphereTags: ["extraordinary", "calm"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "連載中",
      recommendationCatch: "後宮に住む謎の妃が怪異を解く中華ファンタジー",
      recommendedFor: ["中華ファンタジー好き", "後宮もの好き", "美しい世界観好き"],
    },
  },
  {
    title: "烏に単は似合わない",
    author: "阿部智里",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2012-07",
    pageCount: 336,
    publisher: "文藝春秋",
    summaryShort: "八咫烏が人の姿で暮らす異世界「山内」を舞台に、若宮の后候補たちが繰り広げる権謀術数を描く和風ファンタジー。松本清張賞を史上最年少で受賞した阿部智里のデビュー作。美しい和の世界観と衝撃のラストが読者を虜にする。和風ファンタジーや宮廷もの好きにおすすめ。",
    moodTags: {
      emotionalTags: ["emotional"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "八咫烏の世界で繰り広げられる宮廷ファンタジー",
      recommendedFor: ["和風ファンタジー好き", "宮廷もの好き", "どんでん返し好き"],
    },
  },
  {
    title: "狐笛のかなた",
    author: "上橋菜穂子",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2006-11",
    pageCount: 352,
    publisher: "新潮社",
    summaryShort: "人の心が聞こえる能力を持つ少女・小夜と、呪いをかけられた霊狐・野火の出会いから始まる和風ファンタジー。上橋菜穂子が紡ぐ繊細で美しい物語は、日本の原風景と幻想が溶け合う独自の世界観を持つ。野間児童文芸賞受賞。短めで読みやすく、上橋作品の入門にもおすすめ。",
    moodTags: {
      emotionalTags: ["emotional", "heartwarming", "sad"],
      purposeTags: ["immersive"],
      atmosphereTags: ["gentle", "extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "少女と霊狐が織りなす繊細な和風ファンタジー",
      recommendedFor: ["和風ファンタジー好き", "上橋菜穂子入門に", "美しい物語好き"],
    },
  },
  {
    title: "本好きの下剋上 第一部",
    author: "香月美夜",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2015-01",
    pageCount: 340,
    publisher: "TOブックス",
    summaryShort: "本を愛する司書が死後、本のない異世界の少女に転生。本を作るために奮闘する「なろう系」の代表的作品。異世界転生ものでありながら、製紙・印刷技術の発展を軸にした知的な物語展開が他に類を見ない独自性を持つ。累計900万部突破の大ヒットシリーズ。本好きの人に特におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing", "positive"],
      purposeTags: ["immersive", "binge", "easy"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "本を作るために異世界で奮闘する転生ファンタジー",
      recommendedFor: ["本好き", "異世界転生好き", "知的な物語好き"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // ミステリー・推理小説（15作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "容疑者Xの献身",
    author: "東野圭吾",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "mystery",
    publishedDate: "2008-08",
    pageCount: 400,
    publisher: "文藝春秋",
    summaryShort: "天才数学者・石神が隣人の母娘を守るため完璧な偽装工作を仕掛ける。その謎に物理学者・湯川が挑む東野圭吾の代表作。直木賞受賞作であり、犯人の動機と献身的な愛が読者の心を揺さぶる。トリックの巧みさと深い人間ドラマを兼ね備えた、ミステリー好きなら必読の一冊。",
    moodTags: {
      emotionalTags: ["emotional", "sad"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "天才数学者の献身が生む完璧な偽装の謎",
      recommendedFor: ["ミステリー好き", "東野圭吾ファン", "感動作品好き"],
    },
  },
  {
    title: "白夜行",
    author: "東野圭吾",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "suspense",
    publishedDate: "2002-05",
    pageCount: 864,
    publisher: "集英社",
    summaryShort: "一つの殺人事件を起点に、19年間にわたって暗い道を歩き続ける男女の壮絶な運命を描く東野圭吾の最高傑作の一つ。800ページを超える大作ながら、読み始めたら止まらない吸引力を持つ。愛と罪、光と影のコントラストが胸を打つサスペンスミステリー。重厚な物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["sad", "hopeless"],
      purposeTags: ["binge", "immersive"],
      atmosphereTags: ["dark", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "19年間の闇を歩き続ける男女の壮絶な物語",
      recommendedFor: ["東野圭吾ファン", "重厚なミステリー好き", "サスペンス好き"],
    },
  },
  {
    title: "模倣犯",
    author: "宮部みゆき",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "suspense",
    publishedDate: "2005-11",
    pageCount: 1468,
    publisher: "新潮社",
    summaryShort: "連続殺人事件の犯人が劇場型犯罪を仕掛け、メディアと社会を翻弄する。宮部みゆきが5年の歳月をかけて完成させた超大作サスペンス。司法記者、被害者遺族、犯人と、多角的な視点から現代社会の闇を描き出す。芸術選奨文部科学大臣賞受賞。壮大な社会派ミステリーが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hopeless", "hot"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["dark", "tense", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "劇場型犯罪が暴く社会の闇を描く超大作",
      recommendedFor: ["社会派ミステリー好き", "宮部みゆきファン", "重厚な物語好き"],
    },
  },
  {
    title: "火車",
    author: "宮部みゆき",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "court-social",
    publishedDate: "1998-01",
    pageCount: 576,
    publisher: "新潮社",
    summaryShort: "婚約者が突然姿を消した。彼女の過去を追う休職中の刑事が辿り着いたのは、多重債務の闇だった。宮部みゆきが山本周五郎賞を受賞した社会派ミステリーの傑作。カード破産という社会問題を背景に、一人の女性の壮絶な人生を浮かび上がらせる。社会派推理小説が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["dark", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "多重債務の闇に消えた女性を追う社会派ミステリー",
      recommendedFor: ["社会派ミステリー好き", "宮部みゆきファン", "ノンフィクション風好き"],
    },
  },
  {
    title: "犬神家の一族",
    author: "横溝正史",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "classic-mystery",
    publishedDate: "2003-05",
    pageCount: 480,
    publisher: "KADOKAWA",
    summaryShort: "信州の大財閥・犬神家の遺産相続をめぐり次々と起こる猟奇的殺人事件を、名探偵・金田一耕助が解き明かす横溝正史の代表作。映画でも有名な「湖面から突き出る脚」のイメージは日本ミステリー史に燦然と輝く。日本の探偵小説の原点を味わいたい人におすすめの古典ミステリー。",
    moodTags: {
      emotionalTags: ["scary"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["dark", "uneasy", "extraordinary"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "名探偵・金田一耕助が挑む猟奇殺人の謎",
      recommendedFor: ["古典ミステリー好き", "横溝正史ファン", "日本ミステリー入門に"],
    },
  },
  {
    title: "そして誰もいなくなった",
    author: "アガサ・クリスティー",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "classic-mystery",
    publishedDate: "2010-04",
    pageCount: 336,
    publisher: "早川書房",
    summaryShort: "孤島に招かれた10人の男女が、童謡の歌詞通りに一人ずつ殺されていく。アガサ・クリスティーの最高傑作であり、クローズドサークルミステリーの原点。世界累計1億部を超える驚異的ベストセラーで、すべてのミステリーファン必読の一冊。推理小説の面白さを知りたい人の入門書としても最適。",
    moodTags: {
      emotionalTags: ["scary"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["dark", "tense"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "孤島で一人ずつ消えていくクローズドサークルの原点",
      recommendedFor: ["ミステリー入門に", "クリスティファン", "古典好き"],
    },
  },
  {
    title: "オリエント急行の殺人",
    author: "アガサ・クリスティー",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "classic-mystery",
    publishedDate: "2011-04",
    pageCount: 368,
    publisher: "早川書房",
    summaryShort: "豪華列車オリエント急行の車内で富豪が殺される。雪で立ち往生した列車の中、名探偵ポアロが12人の乗客を尋問し真相に迫る。アガサ・クリスティーが仕掛けた驚愕のトリックはミステリー史上最も有名な結末の一つ。映画化も繰り返される不朽の名作で、推理小説好きにおすすめ。",
    moodTags: {
      emotionalTags: ["emotional"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["tense"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "列車密室で名探偵ポアロが挑む驚愕の真相",
      recommendedFor: ["クリスティファン", "推理小説好き", "どんでん返し好き"],
    },
  },
  {
    title: "占星術殺人事件",
    author: "島田荘司",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "honkaku-mystery",
    publishedDate: "2013-08",
    pageCount: 464,
    publisher: "講談社",
    summaryShort: "占星術に基づいて6人の処女の肉体を切り取り「アゾート」を作るという画家の遺書。そして実際に起こった猟奇殺人の謎に名探偵・御手洗潔が挑む。島田荘司のデビュー作にして、新本格ミステリーの原点とされる記念碑的傑作。大胆なトリックに驚かされたい本格ミステリーファンに必読。",
    moodTags: {
      emotionalTags: ["scary"],
      purposeTags: ["thinking"],
      atmosphereTags: ["dark", "extraordinary"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "新本格ミステリーの原点となった衝撃のトリック",
      recommendedFor: ["本格ミステリー好き", "トリック好き", "島田荘司ファン"],
    },
  },
  {
    title: "十角館の殺人",
    author: "綾辻行人",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "honkaku-mystery",
    publishedDate: "2007-10",
    pageCount: 464,
    publisher: "講談社",
    summaryShort: "孤島に建つ十角形の奇妙な館で、大学ミステリ研のメンバーが次々と殺されていく。綾辻行人のデビュー作であり、「新本格ミステリー」ムーブメントの起爆剤となった記念碑的作品。たった一行で世界が反転する衝撃の真相は、ミステリー史上屈指の驚き。推理小説好きなら必ず読むべき一冊。",
    moodTags: {
      emotionalTags: ["scary"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["dark", "tense", "uneasy"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "たった一行で世界が反転する衝撃のミステリー",
      recommendedFor: ["本格ミステリー好き", "どんでん返し好き", "綾辻行人ファン"],
    },
  },
  {
    title: "すべてがFになる",
    author: "森博嗣",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "honkaku-mystery",
    publishedDate: "1998-12",
    pageCount: 352,
    publisher: "講談社",
    summaryShort: "密室から発見された死体と、天才プログラマー・真賀田四季の謎に犀川教授と西之園萌絵が挑む理系ミステリー。森博嗣のデビュー作にしてメフィスト賞受賞作。コンピュータサイエンスと論理学が織りなす知的なトリックは、理系読者を中心に熱狂的な支持を集めた。知的な推理を楽しみたい人におすすめ。",
    moodTags: {
      purposeTags: ["thinking", "intellectual"],
      atmosphereTags: ["calm"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "天才と対峙する知的興奮に満ちた理系ミステリー",
      recommendedFor: ["理系ミステリー好き", "知的な推理好き", "森博嗣ファン"],
    },
  },
  {
    title: "告白",
    author: "湊かなえ",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "suspense",
    publishedDate: "2010-04",
    pageCount: 320,
    publisher: "双葉社",
    summaryShort: "「娘は、このクラスの生徒に殺されたのです」。終業式の日、女性教師の衝撃的な告白から始まる復讐劇。湊かなえのデビュー作にして本屋大賞受賞作。複数の視点から語られる物語は、読み進めるほどに人間の暗部が浮かび上がる。イヤミス（嫌な後味のミステリー）好きにおすすめの衝撃作。",
    moodTags: {
      emotionalTags: ["hopeless"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["dark", "uneasy"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "女性教師の告白から始まる衝撃の復讐劇",
      recommendedFor: ["イヤミス好き", "湊かなえファン", "衝撃的な結末好き"],
    },
  },
  {
    title: "殺戮にいたる病",
    author: "我孫子武丸",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "suspense",
    publishedDate: "1996-11",
    pageCount: 336,
    publisher: "講談社",
    summaryShort: "東京で連続する猟奇殺人事件を、犯人・犯人を追う刑事・犯人の母の三つの視点から描く衝撃のサイコサスペンス。我孫子武丸の代表作であり、ラスト数ページで世界がひっくり返る驚愕の仕掛けはミステリー史上最高峰の叙述トリック。先入観を覆されたい人に強くおすすめ。",
    moodTags: {
      emotionalTags: ["scary", "hopeless"],
      purposeTags: ["binge"],
      atmosphereTags: ["dark", "uneasy"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "ラストで世界が反転する衝撃の叙述トリック",
      recommendedFor: ["叙述トリック好き", "サスペンス好き", "衝撃のラスト好き"],
    },
  },
  {
    title: "64",
    author: "横山秀夫",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "police",
    publishedDate: "2015-02",
    pageCount: 672,
    publisher: "文藝春秋",
    summaryShort: "昭和64年に起きた未解決誘拐殺人事件「ロクヨン」。時効が迫る中、県警広報官・三上は警察組織の壁と報道との軋轢に苦悩する。横山秀夫が14年かけて完成させた警察小説の最高傑作。組織の論理と個人の正義のせめぎ合いを描く骨太な物語は、警察小説好きに必読。",
    moodTags: {
      emotionalTags: ["hot"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["tense", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "警察組織の壁に立ち向かう広報官の戦い",
      recommendedFor: ["警察小説好き", "横山秀夫ファン", "組織ドラマ好き"],
    },
  },
  {
    title: "慟哭",
    author: "貫井徳郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "suspense",
    publishedDate: "1999-04",
    pageCount: 408,
    publisher: "東京創元社",
    summaryShort: "連続幼女誘拐事件を追う捜査一課の刑事と、新興宗教にのめり込んでいく男。二つの物語が交錯するとき、衝撃の真実が明らかになる。貫井徳郎のデビュー作であり、叙述トリックの名作として知られる。人間の孤独と絶望を描きながら、最後の一行で世界を覆す驚きを与えるミステリー好きにおすすめの一冊。",
    moodTags: {
      emotionalTags: ["sad", "hopeless"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["dark", "uneasy"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "二つの物語が交錯するとき明らかになる衝撃の真実",
      recommendedFor: ["叙述トリック好き", "サスペンス好き", "貫井徳郎ファン"],
    },
  },
  {
    title: "氷菓",
    author: "米澤穂信",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "mystery",
    publishedDate: "2001-11",
    pageCount: 240,
    publisher: "KADOKAWA",
    summaryShort: "「やらなくてもいいことなら、やらない」がモットーの省エネ高校生・折木奉太郎が、好奇心旺盛な千反田えるに巻き込まれ日常の謎を解いていく青春ミステリー。米澤穂信のデビュー作にしてアニメ化で大人気の「古典部シリーズ」第一弾。爽やかな推理と青春を楽しみたい人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing", "heartwarming"],
      purposeTags: ["thinking", "easy"],
      atmosphereTags: ["bright", "daily"],
      paceTag: "普通", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "省エネ少年と好奇心少女の爽やか青春ミステリー",
      recommendedFor: ["青春ミステリー好き", "日常の謎好き", "アニメファン"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 経済・ビジネス書（10作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "21世紀の資本",
    author: "トマ・ピケティ",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2014-12",
    pageCount: 736,
    publisher: "みすず書房",
    summaryShort: "200年以上の歴史データを分析し、資本主義社会における格差拡大のメカニズムを解明した経済学の世界的ベストセラー。「r＞g（資本収益率が経済成長率を上回る）」という明快な命題で世界を揺るがした。経済格差や資本主義の未来に関心がある人におすすめの一冊。経済学の初心者でも核心を理解できる構成。",
    moodTags: {
      purposeTags: ["thinking", "intellectual", "learning"],
      atmosphereTags: ["profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      recommendationCatch: "資本主義の格差拡大を200年のデータで解明",
      recommendedFor: ["経済学に興味がある人", "社会問題に関心がある人"],
    },
  },
  {
    title: "マネジメント エッセンシャル版",
    author: "ピーター・F・ドラッカー",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2001-12",
    pageCount: 320,
    publisher: "ダイヤモンド社",
    summaryShort: "経営学の父ドラッカーが「マネジメント」の本質を凝縮したエッセンシャル版。組織の成果を最大化するために必要な考え方と実践を体系的にまとめた経営書の古典。ビジネスパーソンの教養として必読であり、リーダーシップやマネジメントの基本を学びたい人におすすめ。",
    moodTags: {
      purposeTags: ["learning", "work", "intellectual"],
      atmosphereTags: ["profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      recommendationCatch: "経営学の父が語るマネジメントの本質",
      recommendedFor: ["ビジネスパーソン", "マネジメント初心者", "リーダー層"],
    },
  },
  {
    title: "イノベーションのジレンマ",
    author: "クレイトン・クリステンセン",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2001-07",
    pageCount: 320,
    publisher: "翔泳社",
    summaryShort: "なぜ優良企業が新興企業に敗れるのか？「破壊的イノベーション」の概念を提唱し、技術革新と企業経営の関係を根本から問い直した経営学の名著。スタートアップから大企業まで、イノベーションに関わるすべての人の必読書。テクノロジーとビジネスの交差点に興味がある人におすすめ。",
    moodTags: {
      purposeTags: ["thinking", "intellectual", "work"],
      atmosphereTags: ["profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      recommendationCatch: "優良企業がなぜ負けるか？破壊的イノベーションの真実",
      recommendedFor: ["起業家", "ビジネスパーソン", "テクノロジー好き"],
    },
  },
  {
    title: "FACTFULNESS",
    author: "ハンス・ロスリング",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2019-01",
    pageCount: 400,
    publisher: "日経BP",
    summaryShort: "世界はあなたが思うほど悪くない。データと事実に基づいて世界を正しく見る習慣を提案する世界的ベストセラー。人間が陥りがちな10の思い込みを指摘し、データで真実を明らかにする。ビル・ゲイツが「今年読んだ最高の本」と絶賛。物事を正しく判断する力を身につけたい人におすすめ。",
    moodTags: {
      emotionalTags: ["positive"],
      purposeTags: ["learning", "intellectual", "motivated"],
      atmosphereTags: ["bright"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "初心者向け",
      recommendationCatch: "データで世界の見方を変える思考の教科書",
      recommendedFor: ["教養を深めたい人", "ビジネスパーソン", "データ好き"],
    },
  },
  {
    title: "サピエンス全史",
    author: "ユヴァル・ノア・ハラリ",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2016-09",
    pageCount: 536,
    publisher: "河出書房新社",
    summaryShort: "なぜホモ・サピエンスは地球を支配する唯一の人類種となったのか？認知革命・農業革命・科学革命の三つの転機から人類史を壮大に描き直す世界的ベストセラー。歴史・人類学・心理学を横断する知的興奮に満ちた一冊。人類の過去と未来について考えたい人におすすめ。",
    moodTags: {
      purposeTags: ["thinking", "intellectual", "learning"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      recommendationCatch: "人類7万年の歴史を壮大に描き直す知的冒険",
      recommendedFor: ["歴史好き", "教養を深めたい人", "知的好奇心旺盛な人"],
    },
  },
  {
    title: "影響力の武器",
    author: "ロバート・B・チャルディーニ",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2014-07",
    pageCount: 496,
    publisher: "誠信書房",
    summaryShort: "なぜ人は「YES」と言ってしまうのか？返報性・コミットメント・社会的証明・好意・権威・希少性の6つの原理から、人間の意思決定メカニズムを解き明かす社会心理学の名著。マーケティング・営業・交渉に携わるすべての人の必読書であり、日常生活でも役立つ知識が満載の一冊。",
    moodTags: {
      purposeTags: ["learning", "intellectual", "work"],
      atmosphereTags: ["profound"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      recommendationCatch: "人が「YES」と言ってしまう6つの心理原理",
      recommendedFor: ["マーケター", "営業職", "心理学に興味がある人"],
    },
  },
  {
    title: "金持ち父さん貧乏父さん",
    author: "ロバート・キヨサキ",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2000-11",
    pageCount: 272,
    publisher: "筑摩書房",
    summaryShort: "金持ちの父と貧乏な父、二人の父親から学んだお金の哲学を対比しながら語る世界的ベストセラー。「お金のために働くのではなく、お金に働かせる」という考え方を平易な言葉で伝える。お金やファイナンシャルリテラシーについて学び始めたい人の入門書として最適な一冊。",
    moodTags: {
      emotionalTags: ["positive"],
      purposeTags: ["learning", "motivated", "easy"],
      atmosphereTags: ["bright"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      recommendationCatch: "お金の常識を覆す二人の父の教え",
      recommendedFor: ["お金の勉強を始めたい人", "投資初心者", "学生"],
    },
  },
  {
    title: "ゼロ・トゥ・ワン",
    author: "ピーター・ティール",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2014-09",
    pageCount: 256,
    publisher: "NHK出版",
    summaryShort: "PayPal創業者ピーター・ティールが語る、ゼロから新しい価値を創造する起業の哲学。「競争は敗者のすること」「独占こそ成功の証」など、常識を覆す主張が満載。スタンフォード大学での講義がベースとなったスタートアップのバイブル。起業や新規事業に興味がある人におすすめ。",
    moodTags: {
      purposeTags: ["thinking", "intellectual", "motivated"],
      atmosphereTags: ["extraordinary"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      recommendationCatch: "0から1を創造する起業の哲学",
      recommendedFor: ["起業家志望", "スタートアップ関係者", "ビジネスパーソン"],
    },
  },
  {
    title: "スタンフォード式 経済学入門",
    author: "ティモシー・テイラー",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2013-02",
    pageCount: 288,
    publisher: "かんき出版",
    summaryShort: "アメリカで最も人気のある経済学入門講座をベースに、ミクロ経済学とマクロ経済学の基本を一冊にまとめた入門書。需要と供給、GDP、インフレなど経済の基礎概念を身近な事例で解説。経済ニュースが理解できるようになりたい人、経済学を初めて学ぶ人におすすめの一冊。",
    moodTags: {
      purposeTags: ["learning", "intellectual", "easy"],
      atmosphereTags: ["bright"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "初心者向け",
      recommendationCatch: "経済学の基本を身近な事例でわかりやすく解説",
      recommendedFor: ["経済学初心者", "ビジネスパーソン", "学生"],
    },
  },
  {
    title: "父が娘に語る 美しく、深く、壮大で、とんでもなくわかりやすい経済の話。",
    author: "ヤニス・バルファキス",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2019-03",
    pageCount: 248,
    publisher: "ダイヤモンド社",
    summaryShort: "元ギリシャ財務大臣が十代の娘に語りかける形式で、経済の本質をわかりやすく解き明かす。市場・資本主義・格差・仮想通貨といった複雑なテーマを物語のように読める。経済学の専門知識がなくても楽しめる、知的好奇心を刺激される一冊。経済を楽しく学びたい人におすすめ。",
    moodTags: {
      purposeTags: ["learning", "intellectual", "easy"],
      atmosphereTags: ["bright", "gentle"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      recommendationCatch: "元財務大臣が娘に語る世界一わかりやすい経済の話",
      recommendedFor: ["経済学初心者", "教養を深めたい人", "学生"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 歴史小説・時代小説（10作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "竜馬がゆく",
    author: "司馬遼太郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "sengoku-bakumatsu",
    publishedDate: "1998-09",
    pageCount: 480,
    publisher: "文藝春秋",
    summaryShort: "幕末の風雲児・坂本竜馬の生涯を活写する司馬遼太郎の代表作にして国民的歴史小説。自由奔放で型破りな竜馬が、日本の近代化のために東奔西走する姿は世代を超えて読者を魅了する。全8巻の大作だが読みやすく、歴史小説の入門書としても最適。幕末や日本史に興味がある人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive", "binge", "learning"],
      atmosphereTags: ["extraordinary", "tense"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "型破りな坂本竜馬が駆け抜けた激動の幕末",
      recommendedFor: ["歴史小説入門に", "幕末好き", "司馬遼太郎ファン"],
    },
  },
  {
    title: "坂の上の雲",
    author: "司馬遼太郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "modern-history",
    publishedDate: "1999-01",
    pageCount: 480,
    publisher: "文藝春秋",
    summaryShort: "明治維新から日露戦争までの日本の躍進を、秋山好古・真之兄弟と正岡子規の三人を中心に描く壮大な歴史小説。司馬遼太郎の畢生の大作であり、近代国家建設に邁進した明治日本の志と気概が胸を打つ。全8巻の壮大さに身を委ねたい歴史好きにおすすめの名作。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive", "learning"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "明治日本の躍進を描く壮大な国民的歴史小説",
      recommendedFor: ["歴史好き", "司馬遼太郎ファン", "明治維新に興味がある人"],
    },
  },
  {
    title: "燃えよ剣",
    author: "司馬遼太郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "sengoku-bakumatsu",
    publishedDate: "1998-09",
    pageCount: 544,
    publisher: "新潮社",
    summaryShort: "新選組副長・土方歳三の生涯を描く司馬遼太郎の傑作時代小説。武州の農家の倅が「武士になる」という一念で幕末を駆け抜け、最後まで武士道を貫く姿は壮絶にして美しい。新選組好きの入門書として不動の人気を誇る。義と美学を貫く生き様に惹かれる人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional", "sad"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["tense", "extraordinary"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "武士道を最後まで貫いた土方歳三の壮絶な生涯",
      recommendedFor: ["新選組好き", "時代小説入門に", "司馬遼太郎ファン"],
    },
  },
  {
    title: "鬼平犯科帳",
    author: "池波正太郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "jp-history",
    publishedDate: "2000-09",
    pageCount: 400,
    publisher: "文藝春秋",
    summaryShort: "江戸時代の火付盗賊改方長官・長谷川平蔵が、悪を懲らしめながら人情味あふれる捕物を繰り広げる池波正太郎の代表作。料理や江戸の風俗描写も魅力的で、読むだけで江戸の空気を味わえる。テレビ時代劇でも国民的人気を誇る時代小説の金字塔。粋な時代小説が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing", "heartwarming"],
      purposeTags: ["immersive", "easy"],
      atmosphereTags: ["daily", "gentle"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "人情味あふれる江戸の捕物帳",
      recommendedFor: ["時代小説好き", "池波正太郎ファン", "江戸文化好き"],
    },
  },
  {
    title: "剣客商売",
    author: "池波正太郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "jp-history",
    publishedDate: "2002-09",
    pageCount: 384,
    publisher: "新潮社",
    summaryShort: "老剣客・秋山小兵衛とその息子・大治郎が江戸を舞台に活躍する池波正太郎の人気時代小説シリーズ。剣の道を極めた父子の絆と、粋な江戸の人間模様が描かれる。料理描写も豊かで、読後に温かい気持ちになれる。時代小説の醍醐味を味わいたい人におすすめの名シリーズ。",
    moodTags: {
      emotionalTags: ["refreshing", "heartwarming"],
      purposeTags: ["immersive", "easy"],
      atmosphereTags: ["daily", "gentle"],
      paceTag: "普通", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "老剣客と息子が織りなす粋な江戸人情物語",
      recommendedFor: ["時代小説入門に", "池波正太郎ファン", "人情もの好き"],
    },
  },
  {
    title: "天地明察",
    author: "冲方丁",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "jp-history",
    publishedDate: "2012-05",
    pageCount: 496,
    publisher: "KADOKAWA",
    summaryShort: "江戸時代、日本独自の暦を作るという壮大な挑戦に挑んだ実在の天文学者・渋川春海の半生を描く。冲方丁が本屋大賞を受賞した歴史エンターテインメント小説。数学と天文学への情熱、挫折と再起の物語は、理系心をくすぐりつつ感動を与える。知的な歴史小説が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional", "positive"],
      purposeTags: ["immersive", "learning", "binge"],
      atmosphereTags: ["bright"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "日本の暦を変えた天文学者の壮大な挑戦",
      recommendedFor: ["歴史好き", "理系", "本屋大賞好き"],
    },
  },
  {
    title: "のぼうの城",
    author: "和田竜",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "sengoku-bakumatsu",
    publishedDate: "2007-11",
    pageCount: 352,
    publisher: "小学館",
    summaryShort: "豊臣秀吉の関東攻めで唯一落ちなかった忍城の戦いを描く痛快歴史エンターテインメント。でくの坊と呼ばれた城代・成田長親が、2万の大軍を相手に奇策で立ち向かう。和田竜のデビュー作にして映画化もされた大ヒット作。歴史を気軽に楽しみたい人におすすめの痛快歴史小説。",
    moodTags: {
      emotionalTags: ["hot", "refreshing", "funny"],
      purposeTags: ["binge", "easy"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "でくの坊が2万の大軍を迎え撃つ痛快歴史小説",
      recommendedFor: ["歴史小説入門に", "エンタメ好き", "戦国好き"],
    },
  },
  {
    title: "村上海賊の娘",
    author: "和田竜",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "sengoku-bakumatsu",
    publishedDate: "2014-07",
    pageCount: 672,
    publisher: "新潮社",
    summaryShort: "戦国時代、瀬戸内海を支配した村上海賊の娘・景が、織田信長との海戦「木津川合戦」に挑む壮大な歴史小説。和田竜が本屋大賞を受賞した歴史エンターテインメントの傑作。勇猛な女海賊が活躍する痛快な物語と迫力の海戦描写が魅力。歴史好き・冒険好きにおすすめ。",
    moodTags: {
      emotionalTags: ["hot", "refreshing"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["extraordinary", "tense"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "瀬戸内海を駆ける女海賊の壮絶な海戦物語",
      recommendedFor: ["歴史好き", "冒険好き", "本屋大賞好き"],
    },
  },
  {
    title: "蒼穹の昴",
    author: "浅田次郎",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "foreign-history",
    publishedDate: "2004-10",
    pageCount: 576,
    publisher: "講談社",
    summaryShort: "清朝末期の中国を舞台に、貧しい生まれから宦官となった春児と、科挙に合格した梁文秀の二人の若者の運命を壮大に描く浅田次郎の代表作。西太后の宮廷を中心に繰り広げられる権謀術数と、時代の激流に翻弄される人間ドラマは圧巻。中国歴史小説の入門書としておすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional", "sad"],
      purposeTags: ["immersive", "learning"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "清朝末期の中国を舞台にした壮大な人間ドラマ",
      recommendedFor: ["中国史好き", "歴史小説好き", "浅田次郎ファン"],
    },
  },
  {
    title: "重耳",
    author: "宮城谷昌光",
    category: "小説・文学",
    l1Id: "novel", l2Id: "historical-novel", l3Id: "foreign-history",
    publishedDate: "1996-06",
    pageCount: 560,
    publisher: "講談社",
    summaryShort: "春秋時代の中国、晋の公子・重耳（ちょうじ）が19年の放浪の末に覇者となる生涯を描く宮城谷昌光の代表作。宮城谷文学の真骨頂である格調高い文体と、古代中国の壮大なスケールが味わえる。中国古代史の面白さを知りたい人、骨太な歴史小説を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional"],
      purposeTags: ["immersive", "learning"],
      atmosphereTags: ["extraordinary", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "19年の放浪から覇者となった男の壮大な物語",
      recommendedFor: ["中国古代史好き", "宮城谷昌光ファン", "骨太な歴史小説好き"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // ライトノベル（15作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "ソードアート・オンライン",
    author: "川原礫",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2009-04",
    pageCount: 392,
    publisher: "KADOKAWA",
    summaryShort: "デスゲームと化した仮想現実RPG「ソードアート・オンライン」に閉じ込められたプレイヤーたちの生死を賭けた戦いを描くライトノベルの金字塔。累計3000万部を超える大ヒットシリーズの原点であり、VRゲームの臨場感と熱いバトル、そしてキリトとアスナのロマンスが魅力。ゲーム好きにおすすめ。",
    moodTags: {
      emotionalTags: ["hot", "refreshing"],
      purposeTags: ["binge", "immersive", "easy"],
      atmosphereTags: ["tense", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "連載中",
      recommendationCatch: "デスゲームVRで始まる壮大な冒険ラノベ",
      recommendedFor: ["ゲーム好き", "ラノベ入門に", "アクション好き"],
    },
  },
  {
    title: "Re:ゼロから始める異世界生活",
    author: "長月達尊",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2014-01",
    pageCount: 328,
    publisher: "KADOKAWA",
    summaryShort: "異世界に召喚された引きこもり少年スバルが、死に戻りの能力だけを武器に絶望的な運命に何度も立ち向かう。長月達尊が「小説家になろう」発で大ヒットさせたダークファンタジー。何度死んでも諦めないスバルの姿に心を打たれる、異世界転生ものの新たな金字塔。絶望と希望の物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "sad", "hopeless"],
      purposeTags: ["binge", "immersive"],
      atmosphereTags: ["dark", "tense", "extraordinary"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "連載中",
      recommendationCatch: "死に戻りで絶望に挑む異世界ダークファンタジー",
      recommendedFor: ["異世界もの好き", "ダークファンタジー好き", "アニメファン"],
    },
  },
  {
    title: "この素晴らしい世界に祝福を！",
    author: "暁なつめ",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2013-10",
    pageCount: 264,
    publisher: "KADOKAWA",
    summaryShort: "異世界転生したダメ人間カズマと、美しいが残念な女神アクア、爆裂魔法しか使えないめぐみん、マゾヒストの騎士ダクネスが繰り広げるドタバタ冒険コメディ。暁なつめによる大人気ラノベシリーズで、異世界もののお約束をパロディにした笑いが満載。気軽に笑えるラノベを探している人におすすめ。",
    moodTags: {
      emotionalTags: ["funny", "refreshing"],
      purposeTags: ["easy", "binge"],
      atmosphereTags: ["bright"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "残念パーティが繰り広げる異世界ドタバタコメディ",
      recommendedFor: ["コメディ好き", "異世界もの好き", "気軽に読みたい人"],
    },
  },
  {
    title: "薬屋のひとりごと",
    author: "日向夏",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2014-08",
    pageCount: 304,
    publisher: "主婦の友社",
    summaryShort: "中華風の架空帝国の後宮を舞台に、薬学の知識を持つ少女・猫猫が後宮で起きる事件を薬学で解決していく。日向夏による大人気ライトノベルで、謎解きと後宮ロマンスが絶妙に融合。累計2700万部突破、アニメ化でも大ヒット。後宮ものやミステリーが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing"],
      purposeTags: ["thinking", "easy", "binge"],
      atmosphereTags: ["daily", "extraordinary"],
      paceTag: "普通", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "連載中",
      recommendationCatch: "薬学少女が後宮の謎を解く中華ファンタジー",
      recommendedFor: ["後宮もの好き", "謎解き好き", "アニメファン"],
    },
  },
  {
    title: "転生したらスライムだった件",
    author: "伏瀬",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2014-05",
    pageCount: 308,
    publisher: "マイクロマガジン社",
    summaryShort: "通り魔に刺されて死んだサラリーマンが、異世界で最弱モンスター・スライムに転生。しかし規格外のスキルを手に入れ、仲間を集めながら国を作っていく。伏瀬による大人気異世界転生ファンタジーで、国づくりの要素と爽快なバトルが魅力。累計4000万部突破。異世界ものの決定版を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["refreshing", "hot"],
      purposeTags: ["binge", "immersive", "easy"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "連載中",
      recommendationCatch: "スライムに転生して国を作る爽快異世界ファンタジー",
      recommendedFor: ["異世界転生好き", "国づくりもの好き", "ラノベ入門に"],
    },
  },
  {
    title: "無職転生 ～異世界行ったら本気だす～",
    author: "理不尽な孫の手",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2014-01",
    pageCount: 352,
    publisher: "KADOKAWA",
    summaryShort: "34歳無職のニートが交通事故で死に、異世界で赤ん坊として転生。前世の記憶と後悔を糧に、今度こそ本気で人生をやり直す。「なろう系」の原点的作品であり、主人公の成長と人間関係の深さが他の転生ものと一線を画す。異世界転生ジャンルの最高傑作と名高い、人生やり直し物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "emotional", "sad"],
      purposeTags: ["immersive", "binge"],
      atmosphereTags: ["extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "ニートが異世界で人生をやり直す感動の成長物語",
      recommendedFor: ["異世界転生好き", "成長物語好き", "なろう系好き"],
    },
  },
  {
    title: "狼と香辛料",
    author: "支倉凍砂",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2006-02",
    pageCount: 280,
    publisher: "KADOKAWA",
    summaryShort: "行商人ロレンスと狼の化身である少女ホロが、中世ヨーロッパ風の世界を旅しながら商いと経済を巡る冒険を繰り広げる。支倉凍砂のデビュー作で、経済と商売をテーマにした異色のファンタジーラノベ。ロレンスとホロの掛け合いが魅力的で、知的な物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["heartwarming"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["calm", "extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "行商人と狼神が紡ぐ経済ファンタジー",
      recommendedFor: ["知的なラノベ好き", "経済に興味がある人", "ファンタジー好き"],
    },
  },
  {
    title: "涼宮ハルヒの憂鬱",
    author: "谷川流",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "2003-06",
    pageCount: 294,
    publisher: "KADOKAWA",
    summaryShort: "「ただの人間には興味ありません」。非日常を求める型破りな女子高生・涼宮ハルヒと、彼女に振り回される語り手キョンの物語。谷川流のデビュー作にしてライトノベルの歴史を変えた大ヒット作。SFとコメディ、学園ものが絶妙に融合した唯一無二のシリーズ。ラノベの名作を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["funny", "refreshing"],
      purposeTags: ["easy", "binge"],
      atmosphereTags: ["bright", "daily"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "連載中",
      recommendationCatch: "非日常を求める少女が巻き起こすSF学園コメディ",
      recommendedFor: ["ラノベ入門に", "アニメファン", "学園もの好き"],
    },
  },
  {
    title: "とある魔術の禁書目録",
    author: "鎌池和馬",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "modern-fantasy",
    publishedDate: "2004-04",
    pageCount: 312,
    publisher: "KADOKAWA",
    summaryShort: "科学と魔術が交錯する学園都市を舞台に、あらゆる異能を打ち消す右手を持つ少年・上条当麻が、記憶を失った少女インデックスと出会うことから壮大な物語が始まる。鎌池和馬による大人気シリーズの第一巻。独自の世界観と熱いバトルが魅力のライトノベル。能力バトル好きにおすすめ。",
    moodTags: {
      emotionalTags: ["hot", "refreshing"],
      purposeTags: ["binge", "immersive"],
      atmosphereTags: ["tense", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "連載中",
      recommendationCatch: "科学と魔術が交錯する学園都市バトルファンタジー",
      recommendedFor: ["能力バトル好き", "ラノベ好き", "世界観重視の人"],
    },
  },
  {
    title: "魔法科高校の劣等生",
    author: "佐島勤",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "2011-07",
    pageCount: 344,
    publisher: "KADOKAWA",
    summaryShort: "魔法が技術として確立された近未来の日本。魔法科高校に「劣等生」として入学した司波達也が、圧倒的な実力で常識を覆していく。佐島勤による累計2000万部超の大ヒットシリーズ。緻密な魔法体系の設定と、主人公の無双ぶりが魅力。俺TUEEE系が好きな人におすすめのライトノベル。",
    moodTags: {
      emotionalTags: ["refreshing", "hot"],
      purposeTags: ["binge", "immersive"],
      atmosphereTags: ["extraordinary", "tense"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "劣等生の仮面を被った最強の魔法師の学園物語",
      recommendedFor: ["俺TUEEE好き", "学園もの好き", "魔法もの好き"],
    },
  },
  {
    title: "ダンジョンに出会いを求めるのは間違っているだろうか",
    author: "大森藤ノ",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "adventure-fantasy",
    publishedDate: "2013-01",
    pageCount: 326,
    publisher: "SBクリエイティブ",
    summaryShort: "迷宮都市オラリオを舞台に、駆け出し冒険者ベルが英雄を目指して成長していく王道冒険ファンタジー。大森藤ノが描くゲーム的な世界観と、ベルのひたむきな成長が読者の心を掴む。アニメ化でも大人気の通称「ダンまち」シリーズ第一巻。王道の冒険ファンタジーが好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "refreshing"],
      purposeTags: ["binge", "easy", "immersive"],
      atmosphereTags: ["bright", "extraordinary"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      completionStatus: "連載中",
      recommendationCatch: "駆け出し冒険者が英雄を目指す王道ファンタジー",
      recommendedFor: ["冒険ファンタジー好き", "成長物語好き", "アニメファン"],
    },
  },
  {
    title: "86―エイティシックス―",
    author: "安里アサト",
    category: "小説・文学",
    l1Id: "novel", l2Id: "sf", l3Id: "near-future",
    publishedDate: "2017-02",
    pageCount: 312,
    publisher: "KADOKAWA",
    summaryShort: "「戦死者ゼロ」の裏側で、差別された少数民族が無人兵器のパイロットとして戦場に送られる。安里アサトが電撃大賞を受賞したデビュー作。戦争と差別、命の意味を問いかけるシリアスな世界観と、少年少女たちの絆が胸を打つ。ミリタリーSFと人間ドラマを楽しみたい人におすすめ。",
    moodTags: {
      emotionalTags: ["hot", "sad", "emotional"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["dark", "tense"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "連載中",
      recommendationCatch: "差別と戦争を描くシリアスなミリタリーSFラノベ",
      recommendedFor: ["ミリタリーSF好き", "社会派好き", "シリアスなラノベ好き"],
    },
  },
  {
    title: "ようこそ実力至上主義の教室へ",
    author: "衣笠彰梧",
    category: "小説・文学",
    l1Id: "novel", l2Id: "mystery", l3Id: "suspense",
    publishedDate: "2015-05",
    pageCount: 312,
    publisher: "KADOKAWA",
    summaryShort: "進学率・就職率100%を誇る名門校の裏に隠された実力至上主義のシステム。底辺クラスに配属された主人公・綾小路清隆が、その正体を隠しながら学校の闘争を制していく。衣笠彰梧による頭脳戦と心理戦が魅力のライトノベル。頭脳バトル系が好きな人におすすめのシリーズ。",
    moodTags: {
      emotionalTags: ["refreshing"],
      purposeTags: ["thinking", "binge"],
      atmosphereTags: ["tense", "uneasy"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "連載中",
      recommendationCatch: "実力だけがものを言う学校で繰り広げる頭脳戦",
      recommendedFor: ["頭脳戦好き", "心理戦好き", "学園もの好き"],
    },
  },
  {
    title: "オーバーロード",
    author: "丸山くがね",
    category: "小説・文学",
    l1Id: "novel", l2Id: "fantasy", l3Id: "isekai",
    publishedDate: "2012-07",
    pageCount: 424,
    publisher: "KADOKAWA",
    summaryShort: "サービス終了したオンラインゲームの世界に、最強の魔王として取り残された主人公アインズ。NPC達が意思を持ち始めた世界で、アインズは世界征服を目指す。丸山くがねによる異色の異世界ファンタジーで、魔王視点の物語展開が斬新。ダークファンタジーや魔王もの好きにおすすめ。",
    moodTags: {
      emotionalTags: ["refreshing"],
      purposeTags: ["binge", "immersive"],
      atmosphereTags: ["dark", "extraordinary"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      completionStatus: "連載中",
      recommendationCatch: "最強の魔王が異世界征服に挑むダークファンタジー",
      recommendedFor: ["ダークファンタジー好き", "異世界もの好き", "魔王もの好き"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 文学・純文学（10作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "ノルウェイの森",
    author: "村上春樹",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "modern-literature",
    publishedDate: "2004-09",
    pageCount: 560,
    publisher: "講談社",
    summaryShort: "大学生のワタナベが、自殺した親友の恋人・直子と、快活な緑の間で揺れ動く恋愛と喪失の物語。村上春樹の出世作にして日本文学史上最大のベストセラーの一つ。静かな文体の中に深い悲しみと生への希求が込められた、世代を超えて読み継がれる恋愛文学の傑作。文学的な恋愛小説を読みたい人におすすめ。",
    moodTags: {
      emotionalTags: ["sad", "emotional"],
      purposeTags: ["thinking"],
      atmosphereTags: ["calm", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "喪失と再生を描く村上春樹の恋愛文学",
      recommendedFor: ["村上春樹ファン", "文学的恋愛小説好き", "純文学入門に"],
    },
  },
  {
    title: "海辺のカフカ",
    author: "村上春樹",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "modern-literature",
    publishedDate: "2005-03",
    pageCount: 672,
    publisher: "新潮社",
    summaryShort: "15歳の少年「カフカ」が家出をして四国の図書館に身を寄せる物語と、猫と話せる老人ナカタさんの物語が交錯する村上春樹の長編小説。現実と幻想が入り混じる不思議な世界観の中で、少年の自立と成長が描かれる。村上ワールドの真髄を味わいたい人、不思議な物語が好きな人におすすめ。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking", "immersive"],
      atmosphereTags: ["calm", "extraordinary"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "少年と猫と話せる老人が織りなす不思議な物語",
      recommendedFor: ["村上春樹ファン", "幻想文学好き", "純文学好き"],
    },
  },
  {
    title: "雪国",
    author: "川端康成",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "jp-literature",
    publishedDate: "2006-05",
    pageCount: 176,
    publisher: "新潮社",
    summaryShort: "「国境の長いトンネルを抜けると雪国であった」。この有名な書き出しで始まる川端康成のノーベル文学賞受賞作。雪深い温泉町を舞台に、旅の男と芸者駒子の哀しい恋を美しい日本語で描いた純文学の至宝。日本文学の美しさを体験したい人、短い名作を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking"],
      atmosphereTags: ["calm", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "読みごたえあり",
      completionStatus: "完結",
      recommendationCatch: "美しい日本語で描かれた雪国の恋物語",
      recommendedFor: ["日本文学好き", "川端康成ファン", "美しい文章が好きな人"],
    },
  },
  {
    title: "人間失格",
    author: "太宰治",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "jp-literature",
    publishedDate: "2006-06",
    pageCount: 192,
    publisher: "新潮社",
    summaryShort: "「恥の多い生涯を送って来ました」。人間社会に適応できず、酒と女と薬に溺れていく男の半生を描いた太宰治の遺作的傑作。自伝的要素が色濃く反映された文学作品であり、累計発行部数は日本小説の中でトップクラス。生きづらさや人間関係に悩む人に深く突き刺さる、不朽の名作。",
    moodTags: {
      emotionalTags: ["sad", "hopeless"],
      purposeTags: ["thinking"],
      atmosphereTags: ["dark", "profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "人間社会に馴染めない男の壮絶な告白",
      recommendedFor: ["日本文学好き", "太宰治ファン", "文学入門に"],
    },
  },
  {
    title: "こころ",
    author: "夏目漱石",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "jp-literature",
    publishedDate: "2004-03",
    pageCount: 384,
    publisher: "新潮社",
    summaryShort: "「先生」と呼ばれる人物の過去の秘密が、手紙を通じて明らかになっていく夏目漱石の代表作。友情・裏切り・罪悪感・孤独といった人間の普遍的な感情を深く掘り下げた近代日本文学の最高峰。教科書にも採用される不朽の名作であり、日本文学の入門書として全世代におすすめ。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking"],
      atmosphereTags: ["calm", "profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "友情と裏切りを描く近代日本文学の最高峰",
      recommendedFor: ["日本文学入門に", "夏目漱石ファン", "名作を読みたい人"],
    },
  },
  {
    title: "変身",
    author: "フランツ・カフカ",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "foreign-literature",
    publishedDate: "2007-01",
    pageCount: 128,
    publisher: "新潮社",
    summaryShort: "ある朝目覚めると巨大な虫に変身していたセールスマン・グレゴール。家族から疎まれ孤立していく彼の姿は、現代社会の疎外と孤独を鋭く象徴する。フランツ・カフカの代表作にして20世紀文学の金字塔。短い作品ながら読後の衝撃は大きく、文学の奥深さを知りたい人におすすめ。",
    moodTags: {
      emotionalTags: ["sad", "hopeless"],
      purposeTags: ["thinking"],
      atmosphereTags: ["dark", "uneasy"],
      paceTag: "早い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "虫に変身した男が突きつける疎外と孤独の物語",
      recommendedFor: ["海外文学好き", "カフカファン", "短編名作好き"],
    },
  },
  {
    title: "銀河鉄道の夜",
    author: "宮沢賢治",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "jp-literature",
    publishedDate: "1989-06",
    pageCount: 272,
    publisher: "新潮社",
    summaryShort: "孤独な少年ジョバンニが、親友カムパネルラと銀河鉄道に乗って宇宙を旅する幻想的な物語。宮沢賢治の代表作であり、生と死、友情と孤独、そして「ほんとうのさいわい」を問いかける不朽の名作。詩的で美しい文章と深いテーマが融合した、日本児童文学の最高峰。心に残る物語を探している人におすすめ。",
    moodTags: {
      emotionalTags: ["sad", "emotional"],
      purposeTags: ["thinking"],
      atmosphereTags: ["calm", "extraordinary", "gentle"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      completionStatus: "完結",
      recommendationCatch: "銀河を旅する少年が問う「ほんとうのさいわい」",
      recommendedFor: ["日本文学好き", "宮沢賢治ファン", "幻想文学好き"],
    },
  },
  {
    title: "コンビニ人間",
    author: "村田沙耶香",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "modern-literature",
    publishedDate: "2016-07",
    pageCount: 160,
    publisher: "文藝春秋",
    summaryShort: "36歳未婚、コンビニのアルバイト歴18年。社会の「普通」に馴染めない主人公・恵子が、コンビニという場所でだけ「世界の正常な部品」になれる物語。村田沙耶香が芥川賞を受賞した衝撃作。「普通とは何か」を痛快に問いかける、現代を生きるすべての人におすすめの一冊。",
    moodTags: {
      emotionalTags: ["funny"],
      purposeTags: ["thinking"],
      atmosphereTags: ["daily"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "コンビニでだけ「普通」でいられる女性の物語",
      recommendedFor: ["現代文学好き", "芥川賞好き", "短い名作好き"],
    },
  },
  {
    title: "博士の愛した数式",
    author: "小川洋子",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "modern-literature",
    publishedDate: "2005-11",
    pageCount: 256,
    publisher: "新潮社",
    summaryShort: "記憶が80分しか持たない天才数学者と、家政婦の「私」、そして息子ルートの温かな交流を描く小川洋子の本屋大賞受賞作。数学の美しさと人間の絆が静かに響き合う感動の物語。映画化もされた大ヒット作で、数学が苦手な人でも数の世界の美しさに心を打たれる。穏やかな感動を味わいたい人におすすめ。",
    moodTags: {
      emotionalTags: ["emotional", "heartwarming", "healing"],
      purposeTags: ["easy"],
      atmosphereTags: ["gentle", "calm"],
      paceTag: "遅い", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "記憶80分の数学者と家政婦が紡ぐ温かな絆",
      recommendedFor: ["感動作品好き", "数学好き", "穏やかな物語好き"],
    },
  },
  {
    title: "蹴りたい背中",
    author: "綿矢りさ",
    category: "小説・文学",
    l1Id: "novel", l2Id: "literary", l3Id: "modern-literature",
    publishedDate: "2007-04",
    pageCount: 144,
    publisher: "河出書房新社",
    summaryShort: "クラスの中で浮いている女子高生ハツと、同じく孤立しているアイドルオタクの男子にな川。二人の奇妙な関係を瑞々しい感性で描いた綿矢りさの芥川賞受賞作。当時史上最年少での受賞が話題となった。思春期特有の痛みと孤独をリアルに切り取った、青春文学の傑作。若い世代の共感を呼ぶ一冊。",
    moodTags: {
      emotionalTags: ["sad"],
      purposeTags: ["thinking"],
      atmosphereTags: ["daily"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      completionStatus: "完結",
      recommendationCatch: "クラスで浮いた少女の鋭い感性で描く青春文学",
      recommendedFor: ["青春小説好き", "芥川賞好き", "短い名作好き"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // 自己啓発・実用書（10作品）
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "嫌われる勇気",
    author: "岸見一郎",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2013-12",
    pageCount: 296,
    publisher: "ダイヤモンド社",
    summaryShort: "アドラー心理学を青年と哲人の対話形式でわかりやすく解説した大ベストセラー。「すべての悩みは対人関係の悩みである」「課題の分離」「承認欲求を否定する」など、生き方を変える教えが満載。世界累計700万部を突破した自己啓発書の決定版。対人関係に悩む人、自分らしく生きたい人におすすめ。",
    moodTags: {
      emotionalTags: ["positive"],
      purposeTags: ["thinking", "learning", "motivated"],
      atmosphereTags: ["bright"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      recommendationCatch: "アドラー心理学で人生の悩みをシンプルに解く",
      recommendedFor: ["対人関係に悩む人", "自己啓発入門に", "心理学に興味がある人"],
    },
  },
  {
    title: "7つの習慣",
    author: "スティーブン・R・コヴィー",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2013-08",
    pageCount: 560,
    publisher: "キングベアー出版",
    summaryShort: "「主体的である」「終わりを思い描くことから始める」「最優先事項を優先する」など、人生を成功に導く7つの原則を体系的にまとめた自己啓発書の世界的名著。全世界4000万部を超えるベストセラーであり、ビジネスパーソンの必読書。人格を磨き、効果的な生き方を身につけたい人におすすめ。",
    moodTags: {
      purposeTags: ["learning", "motivated", "work"],
      atmosphereTags: ["profound"],
      paceTag: "普通", depthTag: "重い", readingEaseTag: "普通",
      recommendationCatch: "人生を変える7つの原則を体系的に学ぶ",
      recommendedFor: ["自己啓発好き", "ビジネスパーソン", "人生を変えたい人"],
    },
  },
  {
    title: "DIE WITH ZERO",
    author: "ビル・パーキンス",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2020-09",
    pageCount: 280,
    publisher: "ダイヤモンド社",
    summaryShort: "「ゼロで死ぬ」という衝撃的なコンセプトで、人生の限られた時間とお金の最適な使い方を提案する。「いつかやりたい」を「今やる」に変える9つのルールが、人生観を根底から覆す。お金を貯めることより「経験」に投資する生き方を説く、新時代の人生指南書。人生をもっと楽しみたい人におすすめ。",
    moodTags: {
      emotionalTags: ["positive"],
      purposeTags: ["thinking", "motivated"],
      atmosphereTags: ["bright"],
      paceTag: "早い", depthTag: "中程度", readingEaseTag: "初心者向け",
      recommendationCatch: "人生の時間とお金の使い方を根底から覆す",
      recommendedFor: ["人生設計に悩む人", "お金と幸福を考えたい人", "30代以上"],
    },
  },
  {
    title: "思考は現実化する",
    author: "ナポレオン・ヒル",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "1999-04",
    pageCount: 640,
    publisher: "きこ書房",
    summaryShort: "鉄鋼王アンドリュー・カーネギーの助言を受け、20年以上の研究で500人以上の成功者を分析してまとめた成功哲学の古典。明確な目標設定・自己暗示・マスターマインドなど、成功の原則を体系的に解説。自己啓発書の原点として世界中で読み継がれる名著。目標達成に本気で取り組みたい人におすすめ。",
    moodTags: {
      purposeTags: ["motivated", "learning"],
      atmosphereTags: ["profound"],
      paceTag: "遅い", depthTag: "重い", readingEaseTag: "普通",
      recommendationCatch: "500人の成功者を分析した成功哲学の古典",
      recommendedFor: ["目標達成したい人", "自己啓発好き", "起業家志望"],
    },
  },
  {
    title: "夢をかなえるゾウ",
    author: "水野敬也",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2007-08",
    pageCount: 357,
    publisher: "飛鳥新社",
    summaryShort: "ダメなサラリーマンの前に関西弁を喋るゾウの神様・ガネーシャが現れ、毎日一つずつ「課題」を出していく。水野敬也による累計400万部超の大ベストセラー自己啓発小説。笑いながら読めて、実践的な教訓が自然と身につく。自己啓発書が苦手な人でも楽しめる、物語形式の入門書としておすすめ。",
    moodTags: {
      emotionalTags: ["funny", "positive"],
      purposeTags: ["motivated", "easy", "learning"],
      atmosphereTags: ["bright"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      recommendationCatch: "関西弁のゾウの神様が教える人生の教訓",
      recommendedFor: ["自己啓発入門に", "笑える本が好きな人", "読書初心者"],
    },
  },
  {
    title: "学びを結果に変えるアウトプット大全",
    author: "樺沢紫苑",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2018-08",
    pageCount: 272,
    publisher: "サンクチュアリ出版",
    summaryShort: "インプットだけでは成長しない。精神科医・樺沢紫苑が脳科学に基づき、「話す」「書く」「行動する」の3つのアウトプット術を80の具体的メソッドで解説。累計100万部突破の実用書ベストセラー。学んだことを成果に結びつけたいビジネスパーソンや学生におすすめの一冊。",
    moodTags: {
      purposeTags: ["learning", "work", "motivated"],
      atmosphereTags: ["bright"],
      paceTag: "早い", depthTag: "軽い", readingEaseTag: "初心者向け",
      recommendationCatch: "脳科学に基づく80のアウトプット術",
      recommendedFor: ["ビジネスパーソン", "学生", "自己成長したい人"],
    },
  },
  {
    title: "エッセンシャル思考",
    author: "グレッグ・マキューン",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2014-11",
    pageCount: 320,
    publisher: "かんき出版",
    summaryShort: "「より少なく、しかしより良く」。本当に重要なことだけに集中し、それ以外を捨てる技術を説く。グレッグ・マキューンが提唱するエッセンシャル思考は、情報過多・仕事過多の現代人に最も必要なスキル。忙しすぎて成果が出ない人、優先順位をつけられない人におすすめの思考法の本。",
    moodTags: {
      purposeTags: ["thinking", "work", "motivated"],
      atmosphereTags: ["calm"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      recommendationCatch: "本当に重要なことだけに集中する技術",
      recommendedFor: ["忙しいビジネスパーソン", "優先順位に悩む人", "生産性を上げたい人"],
    },
  },
  {
    title: "LIFE SHIFT 100年時代の人生戦略",
    author: "リンダ・グラットン",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2016-10",
    pageCount: 400,
    publisher: "東洋経済新報社",
    summaryShort: "寿命100年時代、従来の「教育→仕事→引退」の3ステージ人生モデルは崩壊する。リンダ・グラットンが提唱するマルチステージの人生戦略は、生涯学び続け、複数のキャリアを持つ新しい生き方を示す。人生設計やキャリアを見直したい人、将来に不安を感じている人におすすめの一冊。",
    moodTags: {
      purposeTags: ["thinking", "learning", "motivated"],
      atmosphereTags: ["bright"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      recommendationCatch: "100年時代のマルチステージ人生戦略",
      recommendedFor: ["キャリアに悩む人", "人生設計したい人", "30-50代"],
    },
  },
  {
    title: "反応しない練習",
    author: "草薙龍瞬",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2015-07",
    pageCount: 224,
    publisher: "KADOKAWA",
    summaryShort: "ブッダの教えをベースに、悩みや怒りの「反応」をコントロールする実践的な方法を解説する。「すべての悩みは心の反応から生まれる」という気づきから、心を穏やかに保つ技術を学べる。マインドフルネスや仏教哲学に興味がある人、ストレスや感情のコントロールに悩む人におすすめ。",
    moodTags: {
      emotionalTags: ["healing"],
      purposeTags: ["thinking", "learning"],
      atmosphereTags: ["calm", "gentle"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "初心者向け",
      recommendationCatch: "ブッダの教えで心の反応をコントロールする",
      recommendedFor: ["ストレスに悩む人", "マインドフルネスに興味がある人", "心を穏やかにしたい人"],
    },
  },
  {
    title: "限りある時間の使い方",
    author: "オリバー・バークマン",
    category: "ビジネス・経済",
    l1Id: "novel", l2Id: "entertainment", l3Id: "easy-masterpiece",
    publishedDate: "2022-06",
    pageCount: 304,
    publisher: "かんき出版",
    summaryShort: "人生はたった4000週間。生産性向上のハックではなく、「限りある時間」という現実を受け入れた上でどう生きるかを問う哲学的時間術。オリバー・バークマンが時間管理の常識を覆し、本当に大切なことに時間を使う生き方を提案する。忙しさに追われている人、人生の優先順位を見直したい人におすすめ。",
    moodTags: {
      purposeTags: ["thinking", "motivated"],
      atmosphereTags: ["calm", "profound"],
      paceTag: "普通", depthTag: "中程度", readingEaseTag: "普通",
      recommendationCatch: "4000週間の人生をどう生きるかを問う哲学的時間術",
      recommendedFor: ["忙しい人", "人生の意味を考えたい人", "哲学好き"],
    },
  },
];

// ── メイン処理 ──────────────────────────────────────────────────────

function main() {
  const booksIndexPath = join(process.cwd(), "src", "data", "books.index.json");
  const supplementPath = join(process.cwd(), "data", "summaries-supplement.json");

  // 1. 既存データ読み込み
  const booksIndex: any[] = JSON.parse(readFileSync(booksIndexPath, "utf-8"));
  const summaries: Record<string, string> = JSON.parse(readFileSync(supplementPath, "utf-8"));

  // 既存IDの集合
  const existingIds = new Set(booksIndex.map((b: any) => b.id));

  const now = new Date().toISOString();
  let addedCount = 0;
  let skippedCount = 0;

  for (let i = 0; i < novels.length; i++) {
    const novel = novels[i];
    const entryId = `novel-100-${String(i + 1).padStart(3, "0")}`;

    if (existingIds.has(entryId)) {
      console.log(`SKIP: ${entryId} (${novel.title}) - 既に存在`);
      skippedCount++;
      continue;
    }

    // books.index.jsonエントリ作成
    const searchParts = [novel.title, novel.author];
    if (novel.publisher) searchParts.push(novel.publisher);
    searchParts.push(novel.category);

    const entry: any = {
      id: entryId,
      title: novel.title,
      authors: [novel.author],
      categories: [novel.category],
      keywords: [novel.category, "T-1101追加"],
      searchableText: searchParts.join(" "),
      updatedAt: now,
      publishedDate: novel.publishedDate,
      language: "ja",
      manualClassification: {
        l1Id: novel.l1Id,
        l2Id: novel.l2Id,
        l3Id: novel.l3Id,
        l4TagIds: ["readable"],
        l5TagIds: [],
      },
    };

    if (novel.publisher) entry.publisher = novel.publisher;
    if (novel.pageCount) {
      entry.pageCount = novel.pageCount;
      entry.estimatedReadingHours = Math.round((novel.pageCount / 40) * 10) / 10;
    }
    if (novel.moodTags) entry.moodTags = novel.moodTags;

    booksIndex.push(entry);

    // workId生成 & summaryShort登録
    const workId = makeWorkId("novel", novel.title, novel.author);
    summaries[workId] = novel.summaryShort;

    addedCount++;
  }

  // 2. ファイル書き出し
  writeFileSync(booksIndexPath, JSON.stringify(booksIndex, null, 2), "utf-8");
  console.log(`books.index.json: ${addedCount} 件追加 (${skippedCount} 件スキップ)`);

  writeFileSync(supplementPath, JSON.stringify(summaries, null, 2), "utf-8");
  console.log(`summaries-supplement.json: ${addedCount} 件のサマリー追加`);

  // 3. 追加作品一覧出力
  console.log("\n=== 追加作品一覧 ===");
  novels.forEach((n, i) => {
    console.log(`${i + 1}. ${n.title} / ${n.author} [${n.l2Id}/${n.l3Id}]`);
  });
  console.log(`\n合計: ${novels.length} 作品`);
}

main();
